### ISSUE TITLE
iFrame percentage size

### ISSUE THREAD

**Issue by grahammcuk** [cbopp-art/lightcase#10]
Is there a way to define the iFrame size in percentages? For example. I would like my iFrame lightbox to open up at 80% width and 80% height of the viewport.

Thanks

**Comment by cbopp-art** [comment]
It should be possible if you initialize your link with following settings:

```javascript
$('#myIframe').lightcase({
	shrinkFactor : 0.8,
	maxWidth : '100%',
	maxHeight : '100%',
	iframe : {
		width : '100%',
		height :'100%'
	},
});
```

**Comment by cbopp-art** [comment]
Did it work for you and could we close this issue?
Thanks for your quick reply.

**Comment by cbopp-art** [comment]
@grahammcuk 
I close this issue now because I didn't got any feedback from you.
In case you still would have troubles with this, feel absolutely free to reopen this issue again.

Thanks!

**Comment by rockstarwebdesign** [comment]
I tried what you suggested and it's not working. The light case image is too small and I can't seem to be able to modify it.
