### ISSUE TITLE
Jump window when close

### ISSUE THREAD

**Issue by Bezponiki** [cbopp-art/lightcase#100]
When i use:
`lightcase.close();`
window sroll up. why?
I used version 2.3.6

**Comment by cbopp-art** [comment]
hmm. strange yes. but there actually were changes to watch scroll interaction while lightcase is open.
probably a side effect?!
Could you might provide a demo or snippet code how you are using this close command (context)?

Thanks in advance!

**Comment by vskavgaci** [comment]
add <!DOCTYPE html> to top of your page.

**Comment by Bezponiki** [comment]
I have `<!DOCTYPE html>`  but page skroll up

**Comment by Key7i** [comment]
I have the same issue with latest version.. I was using v2.3.4 earlier and it was working fine.. Just updated to latest v2.3.6 and close button takes page to top.

**Comment by fhrtms** [comment]
I've created a workaround or new setting named "cacheScrollPosition" for me, it is checked at the relevant parts with _restoreScrollPosition or _cacheScrollPosition.

**Comment by cbopp-art** [comment]
Is fixed in new version 2.4.0.
