### ISSUE TITLE
Stretching video to fullscreen?

### ISSUE THREAD

**Issue by kalmerrautam** [cbopp-art/lightcase#101]
Hey, is there a possibility to stretch video inside lightcase lightbox to 100% screen height? Or at least fixed height in pixels. E.g. 1080px. Or am I doing something wrong? My example: http://brainbow.co/dev/lightcase/
Downloadable html: http://brainbow.d.pr/C1Ii

**Comment by cbopp-art** [comment]
Hi!
try these options to get video to use the full height.
```javascript
maxWidth: '100%',
maxHeight: '100%',
shrinkFactor: 1,
video: {
    // video settings here
}
```

**Comment by kalmerrautam** [comment]
Thanks a lot! : )
After adding fixed width and height under video settings, everything worked like a charm.

`maxWidth: '100%',
 maxHeight: '100%',
 shrinkFactor: 1
 video: {
   width: '1440',
   height: '1080',
}`
