### ISSUE TITLE
Show gallery - multiple images - from only one thumbnail?

### ISSUE THREAD

**Issue by jdeclanflynn** [cbopp-art/lightcase#104]
Dear CBOPP-ART,
I located lightcase after searching through hundreds of others. Lightcase was very easy to implement, and I love it! However, I have a question, not so much of an issue per se. Please forgive me if the answer to my question is in the original documentation. I guess I am just not seeing it. Here is my question... I want to display a single thumbnail and when clicked, I want to display multiple images as lightcase loads. I like the navigation features when there are multiple thumbnails, but I wanted to see if there was a way to do this while only showing one thumbnail. Is this possible?
Thanks for the wonderful product!

**Comment by jdeclanflynn** [comment]
I think I may have found a clunky work-around. Although I am still interested in hearing from you, CBOPP-ART on a better method, this is what I did. I basically create additional DIVs and set the visibility to hidden using the same class="showcase" and data-rel. This is working at the moment. My site is not online, yet or else I'd send you a link.  My code essentially looks like this:

<a href="images/logo1-lrg.jpg" class="showcase" data-rel="lightcase:Branding"><img src="images/branding-box-off.jpg"></a><div style="visibility: hidden;"><a href="images/logo2-lrg.jpg" class="showcase" data-rel="lightcase:Branding"></a>...</div>

Thanks in advance for the help.

**Comment by cbopp-art** [comment]
Hi
Great, glad to hear!
Well, you either need to have further items/links in the HTML markup but hidden, or you can add them via javascript but same approach (maybe also #98 would help you)

**Comment by cbopp-art** [comment]
I'm going to close this one.
