### ISSUE TITLE
Not a Bug - A Suggestion About Touch Events

### ISSUE THREAD

**Issue by sayontan** [cbopp-art/lightcase#105]
This isn't a bug - it is more of a suggestion for documentation. You currently have jquery.events.touch.js as a script required to enable touch. However, given the size of the script (minified 7.6KB), you might want to consider a much simpler one, jQuery Detect Swipe (https://github.com/marcandre/detect_swipe), which, compressed is barely above 1KB. It also offers support for the swipeleft, swiperight, swipeup and swipedown events, so it should pretty effectively replace the jQuery Events script, unless you are using some features of it that cannot be replaced.

**Comment by cbopp-art** [comment]
Thank you for the hint! Anyway, it is not required since it can be optionally included. It is actually possible to include the script suggested by you instead.
