### ISSUE TITLE
Allowing for larger images

### ISSUE THREAD

**Issue by jdeclanflynn** [cbopp-art/lightcase#106]
It appears to me that there is a max-height set for images. I suppose this was done for a good reason. However, I wonder if there is a way for me to increase the allowable max-height? I am using Lightcase for a graphic design portfolio. Particularly for the print section, I'd like to display those images a bit larger than others, but they all seem to be the same height at the moment. Is there any way to alter this? Thanks in advance!

http://www.jdeclanflynn.com

**Comment by cbopp-art** [comment]
Hi @jdeclanflynn 
Have you checked the options, especially http://cornel.bopp-art.com/lightcase/documentation/#property-maxHeight?

Kind regards,
Cornel

**Comment by schmelik** [comment]
One up @Cornel

**Comment by jdeclanflynn** [comment]
Yes, and that worked great! Thank you for your assistance. Awesome product. :)

**Comment by cbopp-art** [comment]
Your welcome!
