### ISSUE TITLE
Different background-colors for video containers vs. images?

### ISSUE THREAD

**Issue by jdeclanflynn** [cbopp-art/lightcase#107]
I attempted to figure this one out a first before posting this question. Don't wanna be a pest. Nevertheless, I do have an issue. I have videos that are different sizes, i.e., some are standard-def (square) and some are HD (widescreen). In the lightcase.js file, I set the width and height for video, and that works great for the 16:9 videos, but for those videos that are not widescreen, I can see the dark gray (#eee) color along the sides, top and bottom, depending on the actual video width and height.

I wondered if it is possible to either set the size of the video 'container' - for the lack of a better word - to black or perhaps allow the 'container' to be whatever size the video's dimensions are, which as I write that sounds technically difficult as the 'container' may not know what size each video is until it loads, if at all. Having said that, I would be happy if the background for the video 'container' was black seeing as most, if not all, of my videos begin with 5 sec of black. 

The same is true for displaying images... I'd prefer if the background was white instead of the dark gray, but changing one color means setting all to that color... at least that has been my experience so far.

Just wondering. Thanks! And sorry for the being a bother. Appreciate it!

**Comment by cbopp-art** [comment]
You would have different values set with `data-lc-type` that you can use for your style overrides, e.g.:
```
#lightcase-case[data-lc-type=video] {
    background: white;
}
#lightcase-case[data-lc-type=ajax],
#lightcase-case[data-lc-type=inline] {
    background: black;
}
...
```
