### ISSUE TITLE
resize method

### ISSUE THREAD

**Issue by quasiperfect** [cbopp-art/lightcase#11]
hi 

thanks for your work

could you please add a resize method so we can force a resize after the content changes ?
i have a iframe that changes content starts with a lot and then remains only a message and it looks bad

**Comment by cbopp-art** [comment]
Hi
Lightcase doesn't know what's going on within an iframe. May you could load your content (html) via ajax instead. Then, this would work like the ajax form demo example.

**Comment by quasiperfect** [comment]
thanks for responding

not sure if i explained what i need

i need something like the resize function from colorbox (http://www.jacklmoore.com/colorbox/)
$.colorbox.resize() 	This allows Colorbox to be resized based on it's own auto-calculations, or to a specific size. This must be called manually after Colorbox's content has loaded. The optional parameters object can accept width or innerWidth and height or innerHeight. Without specifying a width or height, Colorbox will attempt to recalculate the height of it's current content. 

from a iframe you can then call parent.$.fn.colorbox.resize()

if is not something you can implement then no problem
thanks again for your work

**Comment by cbopp-art** [comment]
hi
there is a similar function which does the recalculation but basically just used for internal purposes.
call:
lightcase.resize();

**Comment by quasiperfect** [comment]
ok thanks
