### ISSUE TITLE
Instagram Issue

### ISSUE THREAD

**Issue by Sebsebzen** [cbopp-art/lightcase#112]
I'm trying to directly link to an Instagram picture and have it opened as an image in light box.

https://www.instagram.com/p/BQSInq8glIH/media/?size=l

However, Lightcase only recognizes it as an iframe and it is not contained properly. Is there a way to force display as image? Do I need to pre-fetch the final image location?

```
<a href="https://www.instagram.com/p/BQSInq8glIH/media/?size=l" data-rel="lightcase"></a>
```

**Comment by cbopp-art** [comment]
Yes, actually there is! Just take a look what is possible with options:
http://cornel.bopp-art.com/lightcase/documentation/#property-type

**Comment by Sebsebzen** [comment]
Thanks, could you give me the code snippet?

`data-lc-options="{'type': 'image'}" `

Btw, below a screenshot of the issue

![iframe](https://cloud.githubusercontent.com/assets/6603152/22814356/79a40098-ef85-11e6-8ff2-f6bb6636e72d.png)

**Comment by Sebsebzen** [comment]
Ping!

**Comment by cbopp-art** [comment]
Hi @Sebsebzen 
Unfortunately, I tested it out and came to the conclusion that this doesn't work in any case. I think this could only be done with a workaround, fetching image via ajax, then read dimensions and place it into lightcase accordingly. Probably using one of the hook functions.

**Comment by Sebsebzen** [comment]
Oh, thanks. I did a workaround by calling an inline element with width: 100%; object-fit: contain;

**Comment by cbopp-art** [comment]
Ok, great! So can we close this issue?
Thanks
