### ISSUE TITLE
make "lightcase" for attr optional

### ISSUE THREAD

**Issue by fritzmg** [cbopp-art/lightcase#114]
I am trying to use lightcase and its collections feature with links like this:
```html
<a href="…" data-lightbox="lb491">
   <img …>
</a>
```
which are generated by a CMS. While it is possible to define the data attribute that lightcase uses for initializing collections (see http://cornel.bopp-art.com/lightcase/documentation/#property-attr), lightcase still expects that attribute to start with `"lightcase"`.

As a workaround I am using this instead:
```JavaScript
$('a[data-lightbox]').each(function(){
  $(this).attr('data-lightbox','lightcase:'+$(this).data('lightbox')).lightcase({
    attr: 'data-lightbox'
  })
});
```
https://github.com/fritzmg/contao-lightcase/blob/1.0.0/system/modules/lightcase/templates/j_lightcase.html5#L10-L14
Instead of just
```JavaScript
$('a[data-lightbox]').lightcase({
  attr: 'data-lightbox'
});
```
However, this is rather cumbersome.

**Comment by cbopp-art** [comment]
Hi!
```
$('a[data-lightbox]').lightcase({
  attr: 'data-lightbox'
});
```
basically it should do it.

**Comment by cbopp-art** [comment]
But only if your attribute value has a delimiter with `:`.
Name is irrelevant.
```data-lightbox="lb491:myCollection"```

**Comment by fritzmg** [comment]
> But only if your attribute value has a delimiter with :.
> Name is irrelevant.
> data-lightbox="lb491:myCollection"

Yes I know, that's what I mean essentially. Lightcase requires the syntax for collections to be `SOME_STRING:COLLECTION_IDENTIFIER`. However, in the case of the CMS I mentioned (Contao, [github.com/contao](https://github.com/contao)), the output (for galleries for example) is as follows:
```html
<!-- Collection 1 -->
<a href="…" data-lightbox="lb491" …>…</a>
<a href="…" data-lightbox="lb491" …>…</a>
<a href="…" data-lightbox="lb491" …>…</a>
…

<!-- Collection 2 -->
<a href="…" data-lightbox="af384" …>…</a>
<a href="…" data-lightbox="af384" …>…</a>
<a href="…" data-lightbox="af384" …>…</a>
…
```
The collection is already identified by the content of the collection's data attribute. But since Lightcase requires the collection's data attribute to be prepended by `SOME_STRING:`, I need to apply the aforementioned workaround:
```JavaScript
$('a[data-lightbox]').each(function(){
  $(this).attr('data-lightbox','lightcase:'+$(this).data('lightbox')).lightcase({
    attr: 'data-lightbox'
  })
});
```
i.e. prepending the designated data attribute with `lightcase:`, so Lightcase will recognize the collection for the custom collection data attribute.

Hence my request if it would be possible to omit this requirement. But I understand if you do not want to do that, since every "lightbox" works differently to some degree :).

**Comment by cbopp-art** [comment]
Does the option `slideshow: true` not work?
You need to tell Lightcase somehow that it should be a slideshow.
```
$('[data-lightbox]').lightcase({
  attr: 'data-slideshow', 
  slideshow: true
});
```

**Comment by fritzmg** [comment]
That does not work, because lightcase would still not find the information necessary for the collection. See https://jsfiddle.net/5ecvcs7x/

Whereas this works as expected: https://jsfiddle.net/mms2pkta/

**Comment by cbopp-art** [comment]
Hi!
A change is implemented into the branch v2.3.x

You can do initialization like this now:
```
$('a[data-lightbox]').lightcase({
    attr: 'data-lightbox',
    slideshow: true,
    useAsCollection: true
  });
```

**Comment by cbopp-art** [comment]
@fritzmg Can we close this issue?

**Comment by fritzmg** [comment]
I am not sure. This is implemented in `2.4.0`, right? I tried to test it on jsfiddle, but for some reason it does not work at all: https://jsfiddle.net/uuwxndmy/

May be I am doing something wrong though.

**Comment by cbopp-art** [comment]
Hi!
You did it the right way. But there is one more thing to respect. In your fiddle, since you are going to include external img sources, you have to tell lightcase explicitely that it is an image.

This can be done by setting the option `type: image`. Full example:

```
$('a[data-lightbox]').lightcase({
    attr: 'data-lightbox',
    slideshow: true,
    useAsCollection: true,
    type: 'image'
});
```

**Comment by fritzmg** [comment]
Right, forgot about that :)
