### ISSUE TITLE
data-lc-options not working

### ISSUE THREAD

**Issue by hexplor** [cbopp-art/lightcase#118]
So i have been struggling with following issue. I used your options code 

```
data-lc-options="{'maxWidth':440, 'maxHeight':550}"
```

To alter some lightcase elements width and this is apparently not working. Tried all possible ways. That feature would be super handy but i think there's something wrong ?

If i use data elements to alter lightcase options, should lightcase be called in some other way ? Does it matter that i have other lightcase elements with different options applied or without any additional options ? 

Thanks in advance for reply and thanks for this script. It's awesome :)

**Comment by simmonsr** [comment]
I would also appreciate having this resolved so we can control the width and even margins better.

**Comment by DamirPecnik** [comment]
Any ETA on the solution, this is really needed function that is not working ....

**Comment by cbopp-art** [comment]
Hi!
There was actually an error in the documentation. For this the notation has to look like the following, using the single quotes outside and then for the JSON object the double quotes:
```data-lc-options='{"maxWidth": "440", "maxHeight": "550"}'```

**Comment by hexplor** [comment]
Well that's useful ! Gonna try it immediately :)

**Comment by hexplor** [comment]
Sir @cbopp-art , you're a GOD ! That works :) Thank you so much ! :)
