### ISSUE TITLE
iFrame custom width and height wont override default one

### ISSUE THREAD

**Issue by AbhijitParate** [cbopp-art/lightcase#119]
I tried several combinations, one of them is 

```
$('.preview').lightcase({
                maxWidth : 800,
                maxHeight : 800,
                forceWidth:true,
                forceHeight: true,
                liveResize:true,
                type:'iframe',
                iframe : {
                    width : 800,
                    height :800,
                }
            });
```

I want to iFrame to be 800 X 800 but it won't change from default 800X500.

How can I achieve this.?

**Comment by cbopp-art** [comment]
`forceWidth` and `forceHeight` do respect the max dimensions as well.
So, probably you have to change `maxHeight` as well and set its value to `500`.

**Comment by cbopp-art** [comment]
Check out this change 81dfc0c
