### ISSUE TITLE
$case is not defined

### ISSUE THREAD

**Issue by jelewis8** [cbopp-art/lightcase#12]
When clicking a lightcase link, I get "Uncaught ReferenceError: $case is not defined"

jQuery is present, and all other jQuery functions and plugins work. I've tried isolating just lightcase, with same result.

I'll try duplicating on another site, but this one has me stumped.

UPDATE: I've isolated the page so it's just got jquery 1.10.2 and lightcase. Same issue.
My function call looks like this:
   `$('a[data-rel^=lightcase]').lightcase();`

**Comment by cbopp-art** [comment]
Did you ensure that you call lightcase only after the whole DOM is loaded? Sounds like you have included all javascript sources within the head tag but the function call not beeing executed on document ready.

**Comment by jelewis8** [comment]
I've called lightcase within the document ready function, I've also called it with (window).load, so it definitely is getting loaded after dom is loaded. And, like I said, all my other jquery functions work within that same document ready block. I've also isolated it so just lightcase is loading, and nothing.

This is the weirdest thing, b/c I have used lightcase on literally dozens of other projects without any issues. 

I even tried going back to previous versions, but I get the same problem.

I'm using jquery 1.10.2.

**Comment by jelewis8** [comment]
I figured it out. This is bizarre.

My lightcase stylesheet had an id on it, like this: 
`<link rel="stylesheet" id="lightcase-css" href="css/lightcase.css" type="text/css" media="all" />`

Removing the id="lightcase-css" makes it work. Keeping the id on there causes the "$case is not defined" error.

What would cause this?

**Comment by cbopp-art** [comment]
I figured out that [this line](https://github.com/cbopp-art/lightcase/blob/master/lightcase.js#L618) is producing the error.

This wildcard selector seems to be a bit too generic, obviously. It checks if the neccessary markup is already added or not and will not do the call ```lightcase.settings.markup();``` e.g. in your case.
I will have a look at this and implement an alternative solution which would allow to add id attributes to the markup starting with the  ```lightcase.settings.idPrefix```.

Thanks for your feedback about this issue and let's keep the status open.

**Comment by jelewis8** [comment]
Glad to have helped. I thought I was going crazy for a while.
Keep up the great work, this is a fantastic plugin.

**Comment by cbopp-art** [comment]
@jelewis8 
Fixed and available with the new release [v2.1.0](https://github.com/cbopp-art/lightcase/releases/tag/v2.1.0)
