### ISSUE TITLE
How do I change the timeout in a slideshow?

### ISSUE THREAD

**Issue by fmester** [cbopp-art/lightcase#120]
I've got a slideshow launched via HTML using thumbnails like this:

```
<a data-rel="lightcase:imggallery581:slideshow" data-lc-options="timeout:2000" title="test1" href="img1.jpg">
<img style="width:50px;" src="img1.jpg" />
</a>

<a data-rel="lightcase:imggallery581:slideshow" data-lc-options="timeout:2000"  title="test2" href="img2.jpg">
<img style="width:50px;" src="img2.jpg" />
</a>
```

... etc.

It works fine except data-lc-options="timeout:2000" isn't having any effect i.e. it's not changing the timeout from the default 5000 to 3000 ms. Does anybody know what I'm doing wrong, perhaps my syntax for the options is incorrect?

**Comment by cbopp-art** [comment]
Here is the documentation:
http://cornel.bopp-art.com/lightcase/documentation/#options
