### ISSUE TITLE
Height and Width overrides do not work

### ISSUE THREAD

**Issue by KirbyFox** [cbopp-art/lightcase#122]
I could not get the height and width overrides to work.

Had to resort to editing the lightcase.js file and hard coding dimensions in there.

**Comment by cbopp-art** [comment]
Could you provide an example where I can reproduce the issue?
Thanks in advance!

**Comment by NickMChambers** [comment]
Certainly.

 $('a[data-rel^=lightcase]').lightcase({
      shrinkFactor: 0.9,
      forceHeight: true,
      forceWidth: true,
      inline: {
         height: '1000',
         width: '1000'
      },            
      maxWidth: '1000',
      maxHeight: '900'            
  });

 $('a[data-rel^=lightcase]').lightcase({
      shrinkFactor: 0.9,
      forceHeight: true,
      forceWidth: true,
      iframe: {
         height: '1000',
         width: '1000'
      },            
      maxWidth: '1000',
      maxHeight: '900'            
  });

**Comment by cbopp-art** [comment]
indeed, forcing width or height is not supported for all types of content.

**Comment by cbopp-art** [comment]
@NickMChambers
With this change, dimension handling has improved a lot from the integrators perspective. It is possible to set a default `width` and `height` now on settings toplevel, and it is even possible to override it for each special type if needed. Also maxWidth or maxHeight is respected.

Please let me know asap if this change covers all your needs.
