### ISSUE TITLE
Lightcase (PDF) doesn't show up without resizing window

### ISSUE THREAD

**Issue by Ydalb** [cbopp-art/lightcase#129]
Hello,

OS : MacOS Sierra
Browser : Chrome, latest
jQuery : v2.2.4

I have a little annoying bug : I have a list of link to preview PDF. I'm using the following JS code :
```js
$('a[data-rel^=lightcase]').lightcase({
        showTitle: false,
        showCaption: false,
        swipe: true,
        fullscreenModeForMobile: true,
        useKeys: true,
        shrinkFactor : 0.85,
        maxWidth : '100%',
        maxHeight : '100%',
        iframe : {
            width : '100%',
            height :'100%'
        }
    });
```

When I click on a link to preview a PDF, the modal doesn't show, only the overlay with the cross to close it. I have to manually resize the browser (even 1px) so the modal show up.

Here is two screen of the DOM, you can see on the first, the content's height is 0px. As soon as resize the window manually, the content's height is correctly set.

<img width="955" alt="capture d ecran 2017-04-25 a 23 31 41" src="https://cloud.githubusercontent.com/assets/1888805/25408799/8b0a3f36-2a0f-11e7-8029-ea3d70f9381e.png">
<img width="951" alt="capture d ecran 2017-04-25 a 23 31 52" src="https://cloud.githubusercontent.com/assets/1888805/25408802/8ea61020-2a0f-11e7-8fc4-58c9260078b8.png">

Pictures/Movies preview works well, only PDF are broken. Can't reproduce the bug on Safari (Mac OS).

**Comment by Ydalb** [comment]
:up:

**Comment by cbopp-art** [comment]
Hi!

Lightcase doesn't detect the height of an iframe automatically since iframes have no specific height by nature. You will need to define your preferred height value using the respective option like this:

```
iframe : {
    width : '100%',
    height : '200'
}
```

**Comment by Ydalb** [comment]
Hi @cbopp-art , thanks for your answer.

The property iframe / height : 100% doesn't work !? I have to specify a height in 'px' instead !?

I thought 100% mean 100% of current viewport.

**Comment by cbopp-art** [comment]
I have tested, and it seems that jQuery doesn't handle string values like `100%` to be set via `css()` sometimes, although it should do according to the docs.

However, what you could do as a workaround is:

```
maxWidth: '100%',
maxHeight: '100%',
iframe: {
  width: '100%',
  height: function () { return $(window).outerHeight() }
}
```

**Comment by Ydalb** [comment]
Thank you @cbopp-art :D

It works like a charm !
