### ISSUE TITLE
No horizontal scroll on iframe touch devices

### ISSUE THREAD

**Issue by djmtype** [cbopp-art/lightcase#136]
I have a large horizontal image. On desktop, the iframe displays fine with scrolling in the x direction. On touch devices, the iframe won't scroll. The sizing is correct, but won't scroll. I've tried a number of options which all gave the same result. 
I also tried adding `-webkit-overflow-scrolling: touch; overflow-x: scroll;` to a number of lightcase's classes.

My options: 

```
$('a[data-rel^=modal-html]').lightcase({
transition: 'fade',
maxWidth: 1600,
maxHeight: null,
showTitle: false,
type:'iframe',
  iframe: {
  width: 1600,
  height: 423,
  frameborder: 0
 }
});
```

I even tried width and height options smaller than my screen size.

```
$('a[data-rel^=modal-html]').lightcase({
transition: 'fade',
maxWidth: 300,
maxHeight: 300,
showTitle: false,
type:'iframe',
  iframe: {
  width: 300,
  height: 300,
  frameborder: 0
 }
});
```

**Comment by cbopp-art** [comment]
If I understand your problem correctly, only the content of the iframe is scrolled, but not the whole iframe that's height is larger than the available display height?
Could you may provide a demo fiddle or so?

**Comment by djmtype** [comment]
I was able to go the inline route. But, with the iframe, I had to wrap it inside another div with `overflow-x: scroll`. And set the iframe to `height: 100%` and `width: 100%`. However, that produced unsightly double horizontal bottom scroll bars.
