### ISSUE TITLE
Jump to top issue on mobile

### ISSUE THREAD

**Issue by hello-jason** [cbopp-art/lightcase#14]
Clicking a [demo image](http://cornel.bopp-art.com/lightcase/#demo) in iOS loads up a sexy lightcase, bit it also shoots me back to the top of the page, forcing me to scroll back down every time.

Tested in Safari and Chrome on iOS.

**Comment by campuscodi** [comment]
Same thing on Android devices as well. Tested only Firefox thought.

**Comment by cbopp-art** [comment]
Thanks for reporting. Will get fixed for next release.

**Comment by cbopp-art** [comment]
@hello-jason @campuscodi 
Fixed and available with the new release [v2.1.0](https://github.com/cbopp-art/lightcase/releases/tag/v2.1.0)

**Comment by PrashantTapase** [comment]
I checked with new version but problem is not solved yet

**Comment by cbopp-art** [comment]
@PrashantTapase 
Are you sure? After clearing browser cache? At least for me, everything works fine.
Could you check it again or provide me a live example?

**Comment by PrashantTapase** [comment]
You can check on my live website http://designsunlimited.in/ in mobile version. Lightcase perfectly works on desktop version.

**Comment by schmelik** [comment]
*** NOT A FIX *** (no iOS to test the issue today)
I am not sure if this is related, but I don't like the ability to scroll behind an open lightcase. 
So I  added this class to my css:
.lightcase-open { overflow: hidden !important; }

In it maintains the location of the page and does not allow for scrolling.

**Comment by cbopp-art** [comment]
@PrashantTapase 
In your live website you are using the version 2.0.2. Could you update to 2.1.0 there?

**Comment by PrashantTapase** [comment]
@cbopp-art  Clear your cache. I had update already.

**Comment by cbopp-art** [comment]
You are using a scroll plugin as well. Does your scroll plugin waypoint allow to manipulate something via CSS or on the DocumentObjectModel? It looks like it does not correspond with changes on layout and positioning.
May you need to [refresh](http://imakewebthings.com/waypoints/api/refresh-all/) waypoint after lightcase was getting closed.
For instance you could use this hook ```onCleanup``` to trigger waypoint.
See: http://cornel.bopp-art.com/lightcase/documentation/#hooks

**Comment by PrashantTapase** [comment]
I getting confused. Can u elaborate u answer.

**Comment by cbopp-art** [comment]
I think the problem you have is not caused by lightcase, but you need to refresh waypoint in any case when something has changed on the layout, dimensions, height, overflow.
You can read it in the waypoints documentation:
http://imakewebthings.com/waypoints/api/refresh-all
