### ISSUE TITLE
Lightcase does not trigger for items loaded via AJAX

### ISSUE THREAD

**Issue by SpabRice** [cbopp-art/lightcase#141]
Hello,

I'm using this script a long time and all works very fine.
Now I have a problem.

I have a gallery for example which opens a lightcase image.  This gallery loads new items via ajax (load more button).  But on all item which are loaded via AJAX the lightcax does not trigger and I'm redirected to the href url instead of opening it in the lightcase.

Is there any fix for this?

**Comment by cbopp-art** [comment]
Hi!
Just initialize those links as you do after the page load.

```
$('a[data-rel^=lightcase]').lightcase();
```
