### ISSUE TITLE
go to top issue

### ISSUE THREAD

**Issue by bilios** [cbopp-art/lightcase#144]
Hello! Amazing work friend, i really love to play with lightcase!

I have an issue.. when i call pages to load, everything is fine but the parent goes to top.
I tried to debug but it all happens when this line is triggered (line 188 of lightcase.js | _self._open();)

i cant seem to make it stay to the right place.. Any help?

my setup:
$('.UpdateUserAccount').lightcase({
			showSequenceInfo: false,
			fixedRatio: false,	
			transition: 'elastic',
  			width: '90vw',
  			height: '80vh',
			maxWidth: 900,
			maxHeight: 600,
			iframe: {
    			width: '90vw',
    			height: '80vh',
				frameborder: 0
			}
		});

thanks man!

**Comment by cbopp-art** [comment]
Hi
Thanks!

What exactly do you mean with “parent” goes top?
That the page scrolls back to top?

**Comment by bilios** [comment]
Hey!

I mean, i click a link with this code:
<a class="UpdateUserAccount" data-rel="lightcase" href="newProduct.php">Add new product</a>

and the lightcase set up i send you above, on the line i told you, suddenly the parent window move to the top! The lightcase window is playing correctly, but after i am closing it i have my user on top of the screen.

I tried to address it but i cannot..

I solved it with onInit (i take the pixels from the top) and onCleanup (i move all the page to the correct pixels), but its not the right way.. 

I don't know if it helps, but you can see the problem here, http://symvoli.gr/eVid/index.php if you click the login (you can scroll some pixels so you can see that takes you again to the top). Its only a test but it will help you see the problem! 

Thank you in advance and for your time friend!

**Comment by cbopp-art** [comment]
There is an error in your implementation. Lightcase can’t calculate dimensions, so it seems that your html is invalid. Maybe because you have the Doctype Declaration and <html> tag not at the very first lines of your generated page.
I have no other idea. :(

**Comment by bilios** [comment]
You were right, html was bad, i corrected now the main errors but still.. I will try to find out.. Thank you anyway friend!

**Comment by cbopp-art** [comment]
ok, but i see that your html is still invalid. for instance, there is <div id="AjaxBox"></div> inside the <head> part.

**Comment by bilios** [comment]
I cleaned everything! :) i am passing the w3c tests but still this occur.. Its really weird..

**Comment by bilios** [comment]
the solution was to remove html { overflow-y:scroll; } from the main CSS file! 

Just in case someone else stumble on it!
Case closed! :)

Thanks for your time man!

**Comment by cbopp-art** [comment]
@bilios Great!

**Comment by aiac** [comment]
> the solution was to remove html { overflow-y:scroll; } from the main CSS file!
> 
> Just in case someone else stumble on it!
Thank you, it worked for me after removeing html { overflow-y: auto; }
