### ISSUE TITLE
wrong number of slides

### ISSUE THREAD

**Issue by Mateus-Brito** [cbopp-art/lightcase#145]
In the latest version(2.4.2) with **showSequenceInfo** defined as true, always shows two numbers of slides more than they should (repeat). I did not find anything in the documentation related to this.

Example: If I have two slides, show 4 if I have 6 show 8.

**Comment by cbopp-art** [comment]
I can't reproduce this. Have you proper elements initialized?
Could you provide an example, otherwise it is quite hard to tackle the issue.

Thanks in advance!
