### ISSUE TITLE
jQuery.event.touch is incompatible with jQuery 3+

### ISSUE THREAD

**Issue by retober** [cbopp-art/lightcase#147]
Since your `swipe: true ` relies on `jquery.event.touch` it is not possible to use jQuery 3+. So it is not possible to activate swipe and use the latest jQuery version. Is there any possibility to fix this or are there alternatives to `jquery.event.touch` ?

See:
https://github.com/stephband/jquery.event.move/issues/31

**Comment by cbopp-art** [comment]
Check the new version v2.4.3 with the new jquery.event.touch.js ;)

**Comment by retober** [comment]
I tested it right away. Works now with jQuery 3+. Thanks.

In litecase.js it still says `@version  2.4.2 (27/02/2018)`

**Comment by cbopp-art** [comment]
@retober right, thank you! it should be correct now.
