### ISSUE TITLE
Autoplay not working in chrome

### ISSUE THREAD

**Issue by epcgrs** [cbopp-art/lightcase#151]
youtube autoplay is running normally in firefox, but in chrome it does not work even with 
'[youtube-url] [embed] [ID]?autoplay=1' 
and
```
video {
    autoplay = true
}

```

**Comment by cbopp-art** [comment]
Hi!
This is not an issue of lightcase. Maybe you can check this page:
https://support.bigcommerce.com/articles/Public/How-do-I-make-a-YouTube-video-autoplay

With `[YouTube Video URL]?rel=0&autoplay=1` it doesn't work?

**Comment by epcgrs** [comment]
is not working with either `[YouTube Video URL]?rel=0&autoplay=1` .
by the way when plugin mounts the iframe is putting attr `allow="autoplay"`? 

like 

`<iframe frameborder="0" width="480" height="270" src="[YouTube Video URL]?rel=0&autoplay=1" **allow="autoplay"**></iframe>`

I think after January, 2018 the Google Chrome pause autoplay videos without this attr.

**Comment by epcgrs** [comment]
Sorry. The error is in my application.  😞

**Comment by epcgrs** [comment]
[https://codepen.io/epcgrs/pen/odQeXM](codepen lightcase example)
open in Google Chrome this link.
