### ISSUE TITLE
Add option for html in title

### ISSUE THREAD

**Issue by Pfeifakopf** [cbopp-art/lightcase#152]
Hello,
to add html to the image description would be sometimes really good. If you do this via the title attribute, you can see the html on hover inside the tooltip. An alternativ like data-title would be great.

**Comment by cbopp-art** [comment]
Hi!
Title and caption can also be defined with `data-lc-title` or `data-lc-caption`, respectively.

**Comment by Pfeifakopf** [comment]
Thank you! Perhaps an example in the docs would be good.

**Comment by cbopp-art** [comment]
Good point. Thanks!
This was missing in the docs. I have added it now.
