### ISSUE TITLE
Mixed Galleries - "type" setting

### ISSUE THREAD

**Issue by sayontan** [cbopp-art/lightcase#153]
Hi,
I am trying to use Lightcase with a Flickr Album that has images and videos, and have come across a unique situation. Flickr basically provides URLs in two formats for its videos:

1. Without an extension: https://www.flickr.com/photos/sayontan/42529984021/play/orig/978e3deb0f/
2. As an SWF: https://www.flickr.com/apps/video/stewart.swf?v=384028786&photo_id=42529984021&photo_secret=a0624d0a48

The trouble with the first format of the URL is that if you click on it or try to open it in a browser, it will prompt you to download the MP4 file. Consequently, when I use it with Lightcase and try to open it, I am prompted to download the file. I can get around this by explicitly setting "type: 'video'" when I initialize Lightcase. For the SWF extension there is no such requirement as Lightcase detects the type automatically.

Now, when I take the first format of the URL and co-mingle it with static photos in a gallery, I run into an issue. I cannot explicitly set the type to video since I have images in my data set, and I cannot explicitly set the type for an individual item in the data set (unless I am missing something). I was wondering if there is a way around this. I can use the SWF format, but given the gradual move towards HTML5 videos I would much rather not.

**Comment by cbopp-art** [comment]
Have you tried to force the type `ajax` not `video`?

**Comment by sayontan** [comment]
Thank you for your response, Cornel. 

The `ajax` format isn't helping for mixed galleries, and I keep getting garbled responses for images and CORS policy violation messages for videos. I was wondering about my second question above - can I set the `type` differently for different elements of a gallery? That will help resolve this, I believe.

**Comment by cbopp-art** [comment]
Do you know that you also could pass all options via tag attribute. e.g.
`data-lc-options='{"type": "ajax"}'`

**Comment by sayontan** [comment]
I tried this, but it did not work. However, since I was able to display the Flash videos as a workaround, I am closing this.
