### ISSUE TITLE
Translation of labels

### ISSUE THREAD

**Issue by xillibit** [cbopp-art/lightcase#154]
There are differents labels which are wrote directly in file lightcase.js : 

labels: {
					'errorMessage': 'Source could not be found...',
					'sequenceInfo.of': ' of ',
					'close': 'Close',
					'navigator.prev': 'Prev',
					'navigator.next': 'Next',
 					'navigator.play': 'Play',
'navigator.pause': 'Pause'

Is-there a way to translate them without touch the file lightcase.js ?

**Comment by cbopp-art** [comment]
Hi!
See http://cornel.bopp-art.com/lightcase/documentation/#property-labels
You can tell lightcase the labels and it will take yours.

**Comment by xillibit** [comment]
ok thanks
