### ISSUE TITLE
Display caption text when image is displayed

### ISSUE THREAD

**Issue by xillibit** [cbopp-art/lightcase#155]
Is-it possible to display the caption text of the botton of image before the image is clicked ?

**Comment by cbopp-art** [comment]
If I do understand correctly, you need something similar to this (pure CSS):

```
img::after {
  content: attr(alt);
}
```

**Comment by xillibit** [comment]
I want to display a text like on the first image of this screenshot, but the text should be dispalyed by default without hover with mouse : 

![examples](https://user-images.githubusercontent.com/876395/42443069-c4995680-836c-11e8-9555-f8ff0b8ca2c2.jpg)

**Comment by cbopp-art** [comment]
HI, I think I cannot help you with how you want to layout your page layout and thumbnails. This is a custom implementation for the purpose of demonstration and is not related to the lightcase plugin at all. Sorry.
