### ISSUE TITLE
Using Lightcase for dynamic element?

### ISSUE THREAD

**Issue by Chacapamac** [cbopp-art/lightcase#157]
How can I use Lightcase for dynamic elements ?
This is for a Joomla component (Portfolio Type). 

**My internal code with lightcase is actually**

```<h3 class="mnwall-title">
 <?php if (isset($item->itemLink) && $this->detailBoxTitleLink) { ?>
   <a data-rel="lightcase" href="<?php echo $item->itemLink; ?>&amp;tmpl=component">
     <?php echo $item->itemTitle; ?>
   </a>	
 <?php } else { ?>
<span>
   <?php echo $item->itemTitle; ?>
</span>	
<?php } ?>
</h3>
```
Lightcase Work perfectly for the “in-view” element on my test site —> http://www.grafcomm.ca/graf2/
Front-Page —> Graf Portfolio section

but all element loaded by a “Load More” button (in french(on the site) En voir plus...) are not opening in the lightcase  (even if the surrounding lightcase code is correct) 
My guess is because these element load after lightcase is initialized — I need to re-initialized Lightcase for those element loaded dynamically

Not sure how to proceed ?

**Comment by Chacapamac** [comment]
Thanks, Do you have any infos on how to do that?

**Comment by cbopp-art** [comment]
@Chacapamac Well, you need to initialize lightcase the same way again as you would do the first time.

I actually do not know details about your XHR implementation. But in general maybe something like this?

```
$('.show-more').click(function () {
  $.ajax(...).done(function () {
     // your stuff
     $('.my-item').lightcase({maxWidth: 700, maxHeight: 400});
  });
});
```

**Comment by Chacapamac** [comment]
Thanks, really appreciated.

I will work on it!

**Comment by Chacapamac** [comment]
Thanks Cornel, really appreciated

I will look to it


Good Day !

Patrick Toulze
Graf • Art Director — Marketing Counselor — Social Channels — SEO — Web Mobile
