### ISSUE TITLE
Use within Slick, cancel opening during drag event

### ISSUE THREAD

**Issue by emcniece** [cbopp-art/lightcase#16]
I'm using Lightcase inside a [Slick carousel](http://kenwheeler.github.io/slick/) and the lightbox opens on mouseup after the carousel has been dragged. I'd like to prevent this behavior and only have the lightbox open when a pure click event is performed, not a drag-click.

The first method that comes to mind is to set a global `dragging = true/false` flag that gets updated when the carousel moves, then handle the lightbox clicks accordingly.

Is there any way to prevent the lightbox from opening in Javascript?

**Comment by cbopp-art** [comment]
Hi

To be honest, this sounds more as an issue of the slick carousel itself than one of lightcase. Did you have checked [this issue](https://github.com/kenwheeler/slick/issues/74)?
It seems already to be fixed.

Hope it helps!

**Comment by cbopp-art** [comment]
@emcniece 
Can we close this issue?

**Comment by emcniece** [comment]
Sure. Didn't resolve, as I'm working with a version of Slick that has supposedly been patched... but I agree that this is not a Lightcase issue. Thanks for your help!
