### ISSUE TITLE
Lightcase opens too low on second+ click

### ISSUE THREAD

**Issue by JVKeller** [cbopp-art/lightcase#164]
I'm using lightcase implemented in RocketTheme templates...

The same behavior exists. in all of the instances that I have. 

With Firefox, on the second click, the lightbox openes too low.

https://screenshots.firefox.com/2YGBhHptUlCGLSrE/peppydental.cloudaccess.host

Any ideas?

**Comment by cbopp-art** [comment]
Maybe its a side effect of the web template you're using? Although lightcase is quite safe against external influences and styles, it can happen sometimes that styles from outside can break the calculation of dimensions. You might have to check the stylesheets of your web template to figure out what actually breaks the functionality of lightcase.

**Comment by JVKeller** [comment]
Ended up being AdBlocker Ultimate.

I have my account synced so that's why I saw it on several PC's...

Thank you for the great extension.
