### ISSUE TITLE
[QUESTION] init on dynamically created elements

### ISSUE THREAD

**Issue by sashabeep** [cbopp-art/lightcase#165]
i'm using this simple init for gallery:
```javascript
$('a[data-rel^=lightcase]').lightcase({
			showSequenceInfo: false,
			showCaption: false
		});
```
But this event is not attaching to cloned elements which was created by Owl Carousel. A half of carousel thumbnails opens lightcase, another half after drag - not. How to init them?

**Comment by cbopp-art** [comment]
Hi Sasha

Maybe the cloned elements by the carousel do not clone the events of the elements by passing “true” as argument in the clone() call.
However, maybe you can initialize lightcase after the carousel was initialized, but the carousel plugin will require to provide you a possibility to do this, like a hook or something.

**Comment by sashabeep** [comment]
@cbopp-art moved lightcase init after carousel init, thank you, now everything works as expected
