### ISSUE TITLE
Add images to gallery but only have one image to initialize the gallery

### ISSUE THREAD

**Issue by sdrenth** [cbopp-art/lightcase#172]
Is it possible to have multiple images belong to a single gallery, where only one image will trigger the image to be opened in lightcase?

If the thumbnails are clicked, then the larger image is replaced with the thumbnailed image. Now I want all the thumbnail images to be included in the gallery, but the gallery should only be triggered if the larger image is being clicked upon. But if I add the attribute `data-rel="lightcase:gallery"` to the thumbnail images, they are included in the gallery (which is correct), but if I click on the thumbnail they are also triggering the lightcase gallery which I dont wont.

See the screenshot for more details, so only the top image should trigger the lightcase gallery.

![Screenshot 2019-10-12 at 11 33 33](https://user-images.githubusercontent.com/7802465/66699140-6acc8e00-ece4-11e9-9b00-f942448e129e.png)

**Comment by cbopp-art** [comment]
Hi

First of all, thanks for using lightcase.

Lightcase is indeed very extendable but does not come out with a solution like you consider to implement. Though it would be possible to achieve your desired behavior.
If i understand your needs correctly, you would have to decouple the thumbnails from lightcase and only initialize lightcase after the larger image is clicked.
Just replace the big image every time a thumb is clicked and with that event, initialize lightcase with the new large image and that’s it.
In case you also want to be able to also swipe/slide/move to next or previous items of the gallery directly in the lightcase enlarged view, you could repeat all the thumbs in a hidden container and initializing them with “lightcase:gallery” in your data-rel together with your large image.


Let me know if this works.

Best
Cornel

**Comment by sdrenth** [comment]
@cbopp-art Thank you for taking your time for responding to this issue. I think what you are suggesting would work and solve my problem. I'll go with that for now, although I do think it would be very nice if you also could refresh (reinit) lightcase every time you'd like or to have the possibility to include images in a gallery without it triggering the lightcase gallery view, maybe something for the roadmap  ;)

I'll close this issue for now since your workaround will probably work just as well.
