### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by fusiongt** [cbopp-art/lightcase#18]
Hi love the work you did on this great script! Just wanted to let you know there's a typo in your Docs:

http://cornel.bopp-art.com/lightcase/documentation/

In Mobile you wrote:
[script type="text/javascript" src="path/to/jquery.events.swipe.js"][/script]

But the file changed and is now:
[script type="text/javascript" src="path/to/jquery.events.touch.js"][/script]

Took me a bit to figure it out (as quickly looking at it, the file names look the same as the character numbers match), but think it'll be helpful to others if you fix the typo. Thanks!

**Comment by cbopp-art** [comment]
@fusiongt 
Thanks very much for the hint. It is corrected now.
