### ISSUE TITLE
jQuery (3.5.1) error when inserting inline popup

### ISSUE THREAD

**Issue by szaqal83** [cbopp-art/lightcase#180]
After upgrade to jQuery 3.5.1 and removing jQuery Migrate plugin, error shows:

`Uncaught Error: Syntax error, unrecognized expression: #`

when doing inline insert based to docs:

`lightcase.start({
  href: '#',
  // more options like width, height, etc.
});`

according to [this ](https://github.com/jquery/jquery-migrate/pull/142) pull request of jquery plugin, unquoted attributes were removed (don't know in which version 2.2.0?), I've managed to resolve this by dirty lightcase.js change from this:

`_verifyDataUrl: function (dataUrl) {
			if (!dataUrl || dataUrl === undefined || dataUrl === '') {
				return false;
			}

			if (dataUrl.indexOf('#') > -1) {
				dataUrl = dataUrl.split('#');
				dataUrl = '#' + dataUrl[dataUrl.length - 1];
			}

			return _self._normalizeUrl(dataUrl.toString());
		},`

to this:

`_verifyDataUrl: function (dataUrl) {
			if (!dataUrl || dataUrl === undefined || dataUrl === '') {
				return false;
			}

			if (dataUrl.indexOf('#') > -1) {
				dataUrl = dataUrl.split('#');
				dataUrl = '\\#' + dataUrl[dataUrl.length - 1];
			}

			return _self._normalizeUrl(dataUrl.toString());
		},`

this resolved my problem, don't know if this change doesn't break something else. Setting href to '' in lightcase.start() also worked (without code change) but it is not described in docs and don't know if it is ok to do so.

**Comment by cbopp-art** [comment]
Hi @szaqal83 

Thanks for your investigation. I quickly checked this issue and came to the following conclusion:
It seems that in newest jquery versions it is no longer possible to receive an empty jquery object using `$('#')` as empty element selector but it will still be the case using any faked id `$('#myNotExistingId')`. Important would be to ensure that this id is not used within your html markup so jquery will return an empty jquery object as before using `#` as id selector.
Just use '#myNotExistingId' as value of your href property when starting lightcase.

Best,
Cornel

**Comment by cbopp-art** [comment]
I will add this information to the docs as well.

**Comment by szaqal83** [comment]
Perfect, thnx, works like a charm.
