### ISSUE TITLE
Cleanup removes all key bindings on the page

### ISSUE THREAD

**Issue by Instagit** [cbopp-art/lightcase#19]
The cleanup function removes all key bindings on the page, including those that don't belong to Lightcase.

````
$(document).unbind('keyup');
````

I think namespaced events could help here: https://api.jquery.com/event.namespace/

**Comment by cbopp-art** [comment]
@Instagit 
Thanks for issuing this bug. I added a general namespace ```keyup.lightcase``` because all keyup events are handled with the same anonymous function.

**Comment by cbopp-art** [comment]
Hope this fixes the problematic you had. If yes, I'll appreciate that you confirm and close this issue.
Thanks again!

**Comment by Instagit** [comment]
Perfect, thanks!
