### ISSUE TITLE
Not an issue.. Just wanting to find out

### ISSUE THREAD

**Issue by schmelik** [cbopp-art/lightcase#20]
Is there a way (not in mobile mode) to make an iframe fullscreen not just in mobile.
Preferably it would be responsive as well.. (ie if window < 800px enable fullscreen iframe)

I can do this by overriding the styles but I though there might already be a method.

thanks in advance..

**Comment by cbopp-art** [comment]
Maybe something like this?
```javascript
maxWidth : '100%',
maxHeight : '100%',
iframe : {
    width : '100%',
    height :'100%'
},
onInit : {
    overrideShrinkFactor: function () {
        if ($(window).width() < 800) {
            lightcase.settings.shrinkFactor = 1;
        }
    }
}
```

**Comment by cbopp-art** [comment]
@schmelik
Could you figure out a way? Can I close this issue?

Thanks for your quick feedback!

**Comment by schmelik** [comment]
he he open - close.. open close.. 

Actually I was able to create a css file that handled my needs..
this is what it contained:



    [id^=lightcase],
    [id^=lightcase] *                               { box-sizing: border-box; }

    #lightcase-overlay                              { z-index: 10000; }
    #lightcase-loading                              { z-index: 10001; }
    #lightcase-case                                 { z-index: 10002; }
    #lightcase-nav                                  { z-index: 10003; }
    a[class*="lightcase-icon-"]                     { z-index: 10004 !important; }

    @media screen and (max-width: 500px) {
        .lightcase-contentInner,
        .lightcase-contentInner iframe,
        #lightcase-case .lightcase-content,
        #lightcase-case:not([data-type="error"]) .lightcase-content,
        #lightcase-case                             {   height: 100% !important;
                                                        left: 0;
                                                        margin: 0 !important;
                                                        max-height: none !important;
                                                        max-width: none !important;
                                                        top: 0;
                                                        width: 100% !important;
                                                        padding: 0 !important;
                                                        border: none !important;
                                                    }
    
    /* 640 overrides */
    
        html.lightcase-open                          { height: 100%; }
        .lightcase-open body                        { height: 100%; padding: 0; }
    
        #lightcase-case:not([data-type="image"]):not([data-type="video"]):not([data-type="flash"]):not([data-type="error"]),
        #lightcase-case:not([data-type="image"]):not([data-type="video"]):not([data-type="flash"]):not([data-type="error"]) .lightcase-contentInner,
        #lightcase-case:not([data-type="image"]):not([data-type="video"]):not([data-type="flash"]):not([data-type="error"]) .lightcase-inlineWrap
                                                    { height: 100% !important; }
        #lightcase-case:not([data-type="image"]):not([data-type="video"]):not([data-type="flash"]):not([data-type="error"]) .lightcase-contentInner
                                                    { padding: 50px 0 0 !important; }
    }

**Comment by cbopp-art** [comment]
alright, thanks for your reply. So I close definitively ;)
