### ISSUE TITLE
DisableShrink property doesn't work, case of image type affects type of overlay

### ISSUE THREAD

**Issue by Morjodrom** [cbopp-art/lightcase#22]
First of all, thank you for the plugin.
Perhaps, it's just my misunderstanding of the documentation, but switching disableShrink property to true doesn't affect applying of shrinkFactor, it still does shrink.
Also, having some images names in uppercase I faced a problem of handling it like an iframe. It's not an issue, I guess, but it baffles a bit, it'd be nice to mention it in docs.
Good Luck!

**Comment by cbopp-art** [comment]
@Morjodrom
Thanks a lot for reporting those issues! They should be fixed now with 885951c

**Comment by cbopp-art** [comment]
About the file formats. I changed the code now to compare always lowercase with lowercase. An alternative way is to extend the typeMapping via properties. See: https://github.com/cbopp-art/lightcase/blob/master/lightcase.js#L113

**Comment by cbopp-art** [comment]
Fixed in v2.1.1
