### ISSUE TITLE
Not scrolling in safari mobile

### ISSUE THREAD

**Issue by Bernix01** [cbopp-art/lightcase#23]
It works perfect in chrome mobile but in safari mobile it just won't let me scroll the iframe content... 
Pls help

**Comment by cbopp-art** [comment]
@Bernix01
Hi!
Could you share some more details? I have no problems, neither on a mobile phone using safari.
Thanks!

**Comment by cbopp-art** [comment]
@Bernix01
I close this issue cause I couldn't reproduce same issue by myself neither that I didn't got any feedback.
In case you still would have troubles with this, feel absolutely free to reopen this issue again.

Thanks!
