### ISSUE TITLE
lightbox images goes loop

### ISSUE THREAD

**Issue by Fabbryzz** [cbopp-art/lightcase#24]
Hi, you made a very good plugin!
But I have a problem that I really don't understand. When I click on the images thumbs, the overlay with loader and navigation icons appear, but the images that I would open in lightbox goes loop. i checked the paths and I tried also with external images link, but it don't work.
This is the link of my test page: http://fabbryzz.it/test/lightcase.js/
Can you help me to find the matter? Thanks a lot!

**Comment by cbopp-art** [comment]
Hi @Fabbryzz 
You have a javascript error which can be seen inside the browser console log.
So, when I look to your code where you initialize lightcase, I can see that you passed the arguments (settings) in a wrong way and invalidates your javascript. Actually, arguments needs to be passed within round braces of your ```lightcase.()``` function call.

It should look like this:
```javascript
jQuery(document).ready(function($) {
        $('a[data-rel^=lightcase]').lightcase({'swipe': true});
});
```
If you have ```swipe: true``` you wouldn't need to define it because ```true``` is the default. See [docs](http://cornel.bopp-art.com/lightcase/documentation/#property-swipe).

Hope this fixes your issue!

**Comment by Fabbryzz** [comment]
Thanks for your quick reply cbopp-art, I made a beginner's mistake.. now I have correct the code removing {'swipe': true}, and it seems the code is clean, but it still doesn't work..

**Comment by cbopp-art** [comment]
Try to use double quotes ```"``` for your ```data-rel``` selectors. Something like this:
```$('a[data-rel="lightcase:myCollection:slideshow"]');```

**Comment by Fabbryzz** [comment]
mmh.. nothing to do.. it still doesn't work.. It's a really weird thing.. :-\

**Comment by cbopp-art** [comment]
Could you try with a stable version of jquery (e.g. 2.1.4)?
It also could be that lightcase now got an incompatibility with the new jQuery version or jQuery 3.0.0-alpha which you are using is buggy yet.

**Comment by cbopp-art** [comment]
@Fabbryzz
No! It seems that the element can't get found:
you need to wrap your call for instance with
```javascript
jQuery(document).ready(function($) {
 // Call lightcase only if DOM is ready
});```

**Comment by Fabbryzz** [comment]
I have changed jquery version to 2.1.4 and now it works..!
I have also retrieve the rest of the code at the original version (data-rel without quotes)
The instance - jQuery(document).ready(function($) {... - was already present in the original code, so I don't change nothing else.
It seems that version Alpha of jQuery was the only matter.
Thanks cbopp-art! You've been a great help! ;-)

**Comment by cbopp-art** [comment]
You're welcome!
