### ISSUE TITLE
navigateEndless when useKeys is true

### ISSUE THREAD

**Issue by soufflenin** [cbopp-art/lightcase#25]
1. Many thanks for Lightcase! The thing is great!

2. It looks like “navigateEndless: false” is being ignored when I use the arrow keys on a computer keyboard for moving between images. I can't find a way to fix this. Am I missing something?

**Comment by soufflenin** [comment]
And yes, the same happens with the swiping on mobile: I can easily swipe from the last image in a collection to the first one (there is no the “next” button though).

**Comment by cbopp-art** [comment]
@soufflenin Thanks a lot for reporting!
It's fixed and available in branch v2.1.x or next official release, respectively.

**Comment by soufflenin** [comment]
Thank you!

**Comment by soufflenin** [comment]
I am sorry to say this, but it looks like the issue is still can be experienced on a mobile device, while swiping O_o

**Comment by cbopp-art** [comment]
Fixed for both, key events and swipe gestures.

**Comment by soufflenin** [comment]
You are awesome! Many thanks!
