### ISSUE TITLE
Captions on mobile devices

### ISSUE THREAD

**Issue by soufflenin** [cbopp-art/lightcase#26]
Hello, Cornel!

While testing Lightcase on a mobile device, I stumbled upon this thing: in cases when an image fills the full screen (depends on aspect ratio), the caption falls outside and cannot be read.
Maybe this is not an issue, and I just need to change something in the settings?

Cheers!

**Comment by cbopp-art** [comment]
Hi!
This is related to the styles (e.g. position) given to the caption. For instance, you could place the text so that it overlays the image. Have you already tried this?
Of course, disadvantage in this case would be that less of the image is visible.

Kind regards,
Cornel

**Comment by soufflenin** [comment]
I've tried to play with captions via CSS, but didn't see any effect whatsoever.

I think, it's all about the resizing of images. For example, I look at the same image twice — with a device positioned vertically and then horizontally. In one case a caption is in the right place and I can see it, with another orientation it falls outside.

Of course, my CSS skills are poor (sad but true), but I've got the feeling that there is another reason for the issue. Most likely, I am wrong (:

**Comment by cbopp-art** [comment]
@soufflenin
Ok, i can see the problem in some cases on smaller devices. Let's see what we could do here. But right now I have no idea yet. Even if there is a navigation, the caption wouldn't be readable because navigation would overlay it.

Do you may have a good idea for this?

**Comment by soufflenin** [comment]
I've thought about this, but have no idea so far. Maybe the answer lies somewhere near the limiting of maximum image height? Is it possible to make an additional style rule for small devices (top alignment, perhaps, or forced spacing for captures at the bottom, or something like that)?

**Comment by cbopp-art** [comment]
@soufflenin Fixed with 722a9f2 and available in new release tag v2.1.2. Hope this change also covers your needs.
I'm going to close this issue now.

**Comment by soufflenin** [comment]
Looks like it didn't help, but I just performed a quick check so far.
Thank you for your support anyway!

**Comment by cbopp-art** [comment]
It repositions the title to the top snd left if device width is smaller than 640px.

**Comment by cbopp-art** [comment]
It repositions the title to the top and left if device width is smaller than 640px.

**Comment by soufflenin** [comment]
OK, I'll test it again. Many thanks!
