### ISSUE TITLE
Quick question.

### ISSUE THREAD

**Issue by imdpk** [cbopp-art/lightcase#31]
I am doing some research on lightboxes vs building my own for a project. What I will be doing, is using a API to request data which will be dynamically adding HTML to the page for example to a container element. I am just wondering once I have init your plugin on that container element will additional elements be picked up once added to the div container or will I have to reinit the plugin to pick up the added elements.

Thanks in advance.

**Comment by cbopp-art** [comment]
@imdpk You would have two options in such case: Either you reinitialize, or alternatively use a [hook](http://cornel.bopp-art.com/lightcase/documentation/#hooks) and replace your content on the fly and resizing lightcase afterwards by calling ```lightcase.resize();```

**Comment by cbopp-art** [comment]
Did you find a solution and can I close this issue?
Thanks for short reply.

**Comment by imdpk** [comment]
Thanks for the response sorry for the late response. I ended up using your awesome library and everything see to have worked out. Thanks this issue can be closed.
