### ISSUE TITLE
Close button location

### ISSUE THREAD

**Issue by pear1** [cbopp-art/lightcase#33]
Hello, 

How can I change close button location?
I want to place it under image in line with title.

**Comment by cbopp-art** [comment]
This is no problem. You can change the button position in markup by altering ```lightcase.settings.markup``` as well as adjust style sheets to your needs ([now it has fixed ](https://github.com/cbopp-art/lightcase/blob/master/css/lightcase-min-641.css#L111)).
May you also want to check older versions < 2.x where the close button was placed on the right side above but close to the image.

**Comment by cbopp-art** [comment]
Did you find a solution? I would like to close this issue!
Thanks for a short reply.

**Comment by pear1** [comment]
Yes, I found a solution.
