### ISSUE TITLE
Implement lazy load callback on load

### ISSUE THREAD

**Issue by pkasperski** [cbopp-art/lightcase#34]
Is it possible to somehow implement lazy load functionality for `inline` type, or any other type of content displayed within lightbox ? Thanks in advance

**Comment by cbopp-art** [comment]
@pkasperski
what exactely do you mean with lazy loading the content? To show the box at first and then afterwards loading the content to be shown within the box?

**Comment by pkasperski** [comment]
Correct, when you attach lightcase to an `inline` element, I would like to lazy load images within that inline container. The problem that I'm facing is that the lightbox dimensions are not correctly calculated for inline images that are being lazy loaded. Or maybe there is a way to manually set the lightbox `width` and `height` after the box is shown?

**Comment by cbopp-art** [comment]
yes, thats possible.
just call lightcase.resize();

**Comment by pkasperski** [comment]
Thank you Sir!

**Comment by cbopp-art** [comment]
Can we close this issue?
Thanks for a short reply!

**Comment by pkasperski** [comment]
Yes sir :)

Pozdrawiam / Kind Regards,
Patryk Kasperski
