### ISSUE TITLE
About Intregation with isotope plugin

### ISSUE THREAD

**Issue by boatkung** [cbopp-art/lightcase#35]
I use isotope plugin and I need to update lightcase when I filter some images by isotope (use lightcase collection that image still show only). Can lightcase handle this?

Isotope: http://isotope.metafizzy.co/

Thanks.

**Comment by cbopp-art** [comment]
Hi!
Actually yes, should be possible! Just initialize lightcase using ```lightcase.init();``` like you do after page load.

**Comment by cbopp-art** [comment]
Could you find a solution together with isotope plugin?
And can we close this issue?

**Comment by boatkung** [comment]
Yes, I resolved by update plugin to version 2.3.1 then use "useCategories" API.

When I click each category button then set <strong>useCategories: true</strong> for show some images in that category
and when I click [ALL] button then set <strong>useCategories: false</strong> for show all images

Maybe there are better way to do like this but I don't know much about coding. :laughing: 

Thanks for great plugin. :+1:

**Comment by nickpish** [comment]
Hi @boatkung I'm trying to implement something similar w/ Isotope and Lightcase. Would you share the solution you came up with for toggling the `useCategories` option? Thanks!

**Comment by boatkung** [comment]
Oh Sure! @nickpish
Try to check this one. I rewrite it from my messy code. LOL
https://jsfiddle.net/boatkung/kcawrogo/

Hope that help :smile:

**Comment by nickpish** [comment]
@boatkung Thanks so much! I'll take a look at your approach! :)
