### ISSUE TITLE
SVG image on the page looks weird after lightcase open-close on Windows Phone

### ISSUE THREAD

**Issue by sashabeep** [cbopp-art/lightcase#36]
I have logotype in svg format on the page, this is the only one svg image, and after closing lightcase, size of image (or viewbox?...) changing to different... Tried with different html classes - no wrong cascade or other. With png format nothing happened after close

http://imgur.com/3Y8nCPd

**Comment by cbopp-art** [comment]
Hmm, sounds quite strange. Probably, setting a height for this logo would solve it?

**Comment by sashabeep** [comment]
Yes,setting a height it fixing this problem, but logo will have fixed width instead of 100%
i will try to set height with js based on default size

**Comment by cbopp-art** [comment]
and if you set height: auto;?

**Comment by sashabeep** [comment]
tried to set height auto earlier - no effect

**Comment by cbopp-art** [comment]
i mean setting it with css

**Comment by sashabeep** [comment]
Yes, tried height:auto in css class
Now i'm just get width and set css height using width/height ratio - works
