### ISSUE TITLE
lightcase-contentInner crop content with 100% width border-box elements

### ISSUE THREAD

**Issue by sashabeep** [cbopp-art/lightcase#37]
My form input fields always use border-box to fit 100% of parent width with padding and border without headache. But it crops. Strange, it's more than 100% width of .lightcase-contentInner on the small screen

Full page screenshot
![Wrong crop](http://i.imgur.com/urmwGTY.gif)

fixed by adding +box to .lightcase-contentInner
![Wrong crop](http://i.imgur.com/VbNO1ps.gif)

**Comment by cbopp-art** [comment]
I think it is fixed now with this change e25e11c, right?
