### ISSUE TITLE
Call parent.lightcase 

### ISSUE THREAD

**Issue by schmelik** [cbopp-art/lightcase#40]
Again with a question not an issue.. (this is a solid product)

So I am working in an environment that uses iframes. Is there a way for me to call the parent.lightcase function from within an iframe?
This will allow the #lightcase-overlay to cover the entire page, not just the iframe.

thanks in advance.

**Comment by cbopp-art** [comment]
Hi!
Doesn't it work using ```parent.lightcase.start({href: '#', // more options...});```?

**Comment by schmelik** [comment]
I'll try it unfortunately not today other things are now on my plate.

**Comment by schmelik** [comment]
I finally got to this.. and yes this worked great.
I am just having issues with sizing the window..
