### ISSUE TITLE
Iframe is not scrolling on android device

### ISSUE THREAD

**Issue by zychu** [cbopp-art/lightcase#44]
To reproduce bug please go to this website:

http://www.stogda.pl/offer/shipbuilding/

and click on last tab called 'references'. Then scroll down and click on 'view' button under 'References List'.

Strange thing cause all other instances with images are working great. Problem exists only with android devices. Iframe scrolls smooth on desktops nad iOS devices.

By the way it's amazing plugin. Great work.

**Comment by cbopp-art** [comment]
Hi!
Is it probably a general issue that android doesn't support ```overflow: auto;```?
Right now I don't know how this could be fixed.
Do you may know a good workaround or alternative?

**Comment by zychu** [comment]
Hi,

i've found walkaround for that, it's working for 7inch devices, have to test it with smaller android mobile device.

jquery on document.ready()

```
var ua = navigator.userAgent.toLowerCase();
    var isAndroid = ua.indexOf("android") > -1; // only for android devices
    if(isAndroid) {
      jQuery( ".references_open img, .references_open span" ).on( "click", function() {
        setTimeout(function(){
          jQuery('.lightcase-inlineWrap').addClass('fixed_sizes');
          var new_height = jQuery(window).height()-50; // little offset
          jQuery('#lightcase-hack').remove();
          jQuery( "<style id='lightcase-hack'>body #lightcase-case:not([data-type=image]):not([data-type=video]):not([data-type=flash]):not([data-type=error]) .lightcase-contentInner > *:not(iframe).fixed_sizes { overflow-y: scroll; height: "+new_height+"px !important; }</style>" ).appendTo( "head" );
        }, 500);
      });
    }
```

Giving a height in pixels and forcing overflow-y is enabling smooth scrolling on android devices without any additional scripts. Maybe this will help you to update your script.

Cheers.

**Comment by cbopp-art** [comment]
Wouldn't it also be fixed to when type:inline is excluded from this style ```max-height: none !important;```
https://github.com/cbopp-art/lightcase/blob/master/src/scss/components/modules/_content.scss#L60

**Comment by cbopp-art** [comment]
This should work with newer versions (2.3.x) of lightcase. Please feel free to reopen it is still a common issue.
