### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by igidas** [cbopp-art/lightcase#45]
Hello, 

First, thanks for you work.
Second, is there a way to change labels?

I see there is _self.labels object, but as I understand, it's private and can't be changed.

**Comment by cbopp-art** [comment]
Hi!
Yes, it is private yet. Will make this accessible from public context for next release. ok?
Thanks for issueing!

**Comment by cbopp-art** [comment]
Next minor release will come within the next 3 days!

**Comment by igidas** [comment]
Ok, thanks for an answer!

**Comment by cbopp-art** [comment]
Until the change has been released, you can use branch v2.3.x. All labels/translations can be adjusted via lightcase settings now.
