### ISSUE TITLE
Font path variable in SASS

### ISSUE THREAD

**Issue by ninetienne** [cbopp-art/lightcase#46]
Thanks for Lightcase. Could you please add font path as a variable in the _settings.scss?

**Comment by cbopp-art** [comment]
Good point, sure!

**Comment by cbopp-art** [comment]
Should be configurable now! Can we close this issue now?
Thanks for short reply.

**Comment by ninetienne** [comment]
Thanks for your quick response. Could you please update bower too?

**Comment by cbopp-art** [comment]
It's now available in release v2.3.3

**Comment by ninetienne** [comment]
Thanks a lot!
