### ISSUE TITLE
Images don't show on swipe in ver. 2.3.3

### ISSUE THREAD

**Issue by szaqal83** [cbopp-art/lightcase#47]
After update to ver. 2.3.3 images don't load on swipe, background size is being updated but image doesn't show. I've checked the demo but you have still ver. 2.3.2 which works ok on swipe so I couldn't verify if is it a global bug or my.

**Comment by cbopp-art** [comment]
Hi!
Demo is updated to version 2.3.3 and swipe is still working. Anyway, this small update couldn't have something to do with swipe mechaninsm since there actually was no related change to it at all.

**Comment by szaqal83** [comment]
After downgrade to 2.3.2 without init code change it works fine. To be precise it's not "on swipe" but prev/next problem, after clicking prev/next background stays gray. My init attrs are:
```
attr: 'rel',
showTitle: false,
showCaption: false,
showSequenceInfo: false,
swipe: true
```

**Comment by cbopp-art** [comment]
Thanks! Indeed, version 2.3.3 has beared a bug with in transition. Is fixed and will be available in v2.3.4 event today.

**Comment by cbopp-art** [comment]
v2.3.4 has been released!

**Comment by szaqal83** [comment]
No problem, cheers.
