### ISSUE TITLE
Add option to close lightcase through function

### ISSUE THREAD

**Issue by sohaibaziz** [cbopp-art/lightcase#49]
Hello guys,
First of all great work - its really awesome specially for ajax content .
It would be really really easy to handle lightcase - if you guys can add an option to close lightcase via function which is accessible globally.
So if we want to close it we could simply call that function from a button,link & call close function.

As currently only option to close it is through closeOnOverlayClick or clicking it on close button.

**Comment by cbopp-art** [comment]
Hi
first, thanks a lot for your feedback. this is possible
already. Just call lightcase.close() which is
public.

**Comment by sohaibaziz** [comment]
Awesome :) Thanks a bunch ! 
You really saved me alot of time :+1:
Keep up the good work fella :tada:
