### ISSUE TITLE
Iframe is not scrolling on all iDevices

### ISSUE THREAD

**Issue by eugen-notter** [cbopp-art/lightcase#50]
When calling a longer page in iFarme on a iPad or iPhone, the content cannot be scrolled.
See a demo here:
http://81.221.34.38/different/lightbox/lightcase/

**Comment by cbopp-art** [comment]
@eugen-notter Does the change also fix that issue in your implementation?

**Comment by eugen-notter** [comment]
Unfortunately not. I still cannot scroll the content and the iframe window still bypasses the device size ind landsape mode.

**Comment by cbopp-art** [comment]
Which device versions areyou using? Could you provide any screenshots facing this issue, because for me also the implementation in your demo work now and I'm able to scroll the iFrame content.

Thanks in advance!

**Comment by eugen-notter** [comment]
[lightcase.docx](https://github.com/cbopp-art/lightcase/files/120679/lightcase.docx)

I am using iPhone, iPad mini and iPad. All latest OS. 
Basically the same Problems on all devices.
Id got the files from github one more time to make sure I use the latest versions.

**Comment by cbopp-art** [comment]
Hmm, I can scroll down all iframe content. Everything like expected (using Safari iPhone 5s)!

**Comment by eugen-notter** [comment]
A  also have an iPhone 5s available. It also works with me.
Closing x scrolls out of sight (same as on iPhone6) but content is fully accessible.

**Comment by cbopp-art** [comment]
Well, iOS devices sizes iframes to the full height of content. No chance to change this in any kind of way.

**Comment by eugen-notter** [comment]
I did also investigate this issue a bit and found quite some resources discussing this.
I allow to post some links I considered promising.

https://davidwalsh.name/scroll-iframes-ios
http://techiepulkit.blogspot.ch/2014/09/iframe-ios-7-safari-issues-workarounds.html
https://www.smashingmagazine.com/2014/02/making-embedded-content-work-in-responsive-design/
https://css-tricks.com/forums/topic/iframe-scrolling-problems-in-ios-iphone-5-6/

**Comment by cbopp-art** [comment]
Shouldn't be an issue anymore at least with newer versions of lightcase. Please feel free to reopen if this is still not yet working.

**Comment by fritzmg** [comment]
I am still encountering this issue with version `2.5.0`. Is there really no way to fix this reliably?
