### ISSUE TITLE
Website Documentation Correction

### ISSUE THREAD

**Issue by Diyzzuf** [cbopp-art/lightcase#51]
Hi,
On the documentation, in your website, they are a little missing character, `^` after `data-rel`
[In Mobile => Swipe ](http://cornel.bopp-art.com/lightcase/documentation/#mobile) it's not
```
$('a[data-rel=lightcase]').lightcase({
    swipe: true
});
```
But :
```
$('a[data-rel^=lightcase]').lightcase({
    swipe: true
})
```

**Comment by cbopp-art** [comment]
Thanks! Well it is not a real issue since it doesn't matter what you actually take as element selector. But I agree that it is more consistent when using same wildcard selector as used previously in docs.
Has been corrected now!

**Comment by Diyzzuf** [comment]
Good :), and good job for this plugin.
It's an issue when you use Collections or Slideshow, like `<a href="path/to/media1.jpg" data-rel="lightcase:myCollection">Your link description or thumb</a>`
Without the `^`, it doesn't work for me.
