### ISSUE TITLE
Pop up images are not proportional

### ISSUE THREAD

**Issue by seewhy17** [cbopp-art/lightcase#52]
Works well in Firefox, but not in Google Chrome,  the pop up photo scales inproportionately and looks terrible as found here http://www.yemiajalastudios.com/fashion

**Comment by cbopp-art** [comment]
Hi!
The problem can be found in your html inline styles which affects lightcase (see screenshot).
Could you find a way to remove it or stop making it taking effect for images within lightcase?

![screen shot 2016-02-03 at 12 05 59](https://cloud.githubusercontent.com/assets/2764787/12780502/b3a1d7f8-ca6e-11e5-8929-097f08524404.png)

**Comment by seewhy17** [comment]
yeah, thanks a lot, that fixes the issue, I moved that block of CSS to the mobile specific style, which is where i needed it, <3 lightcase
