### ISSUE TITLE
Examples of Use

### ISSUE THREAD

**Issue by JuanBreva** [cbopp-art/lightcase#53]
Hi there.

First of all, thanks for this plugin. It's beautiful and easy to use.

My problem with it is, as an absolute noob I am, that I can make it work but I cannot get any of the effects from your 'examples of use' gallery working. When I click on the <a> element, it opens the image, but no close button, no spinner on loading, no fade in effect... Just a plain dark background and the image, that's all.

Can you think of something I'm doing wrong? Something else that should be added to my code?

Thanks!

**Comment by cbopp-art** [comment]
Hi!

I’m pleased that you like that plugin!
Well, hard to say what you’re actually doing wrong. What does your Web-Inspector (Console) say, robably any errors?

Do you have a demo page?

**Comment by JuanBreva** [comment]
Thanks a lot for your prompt reply. Sorry I couldn't take a look to it earlier, it's been a quite hectic week.

Unfortunately, I'm developping it local, so I don't have any online source for you to take a look. The Console throws no errors related with Lightcase, at all. So as you can imagine, I'm totally lost here.

Perhaps you can provide me with an email so I can forward to you that precise piece of code?

Thank you very much!
