### ISSUE TITLE
hidden gallery unable to open

### ISSUE THREAD

**Issue by flamner** [cbopp-art/lightcase#54]
Hi, I have big problem with this plugin. My goal is to open slideshow/gallery by button click and not to display gallery thumbnails. It didn't work when I hide/add display:none to gallery(links) container and/or I didn't add something inside `<a></a>` Is any chance to make it works?

js:

```
var clickBtnLink = $('#article-id').find('.gallery-links a').eq(1).attr('href');
     $('.open-gallery').click(function(){
          lightcase.start({href: clickBtnLink});
});
```

html:

`<button class="open-gallery">open</button>
`

```
<div class="gallery-links">
<a href="url-to-image" data-rel="lightcase:slideshow-set" class="">have to be something here</a>
</div>
```

**Comment by cbopp-art** [comment]
Hi!
It would work if you hide just the parend element of your gallery container. Otherwise ```display: none``` would persist for that element within opened lightcase.

**Comment by cbopp-art** [comment]
@flamner Just to ask back: Could you find a working solution?
I would be glad if we could close this issue.

**Comment by karlmuhust** [comment]
You could mimic the click (thats what i did with the same problem)
`
$('.open-gallery').click(function(e){
 e.preventDefault();
 $(".gallery-links a").first().click();
});
`
