### ISSUE TITLE
Youtube/Vimeo issue

### ISSUE THREAD

**Issue by SpabRice** [cbopp-art/lightcase#56]
Hello,

when trying to open a vimeo or youtube video (iframe mode) there are some issues on the player controls:

Youtube: Controls are gone
Vimeo: Fullscreen button/option not showing

Is this a known bug?  How can I solve it?
On the lightcase demo site (http://cornel.bopp-art.com/lightcase/) the issue is also happening on the youtube iframe button.  Click on play and will see that no controls (pause,volume,...) are showing.

*EDIT: 
Just noticed, that the youtube issue is only visible on firefox (chrome,safari works fine).
The "fullscreen" option for vimeo videos are missing in all browsers.

**Comment by SpabRice** [comment]
Still having issues with this.
The youtube issue is related to firefox, and is probably a browser related bug, but the vimeo issue is definately comming from the script.
Any help on that.

**Comment by cbopp-art** [comment]
Hi!
For youtube, does the following information might help?
https://support.google.com/youtube/answer/6276924

**Comment by cbopp-art** [comment]
I'm sorry. Haven't seen that fullscreen only was a problem with vimeo.
Anyway, I couldn't reproduce that error on newer firefox versions 45/46 but with older version 42.
So this definitely doesn't look like a bug of lightcase since that content within iframe cannot be influenced in any kind of way.

**Comment by SpabRice** [comment]
Thanks for your answer.
The youtube is related to firefox, so don't worry about this.

Vimeo:
The issue is visible on all major browsers (firefox,chrome,safari) which is strange.
I did a testcase here:  http://spab-rice.com/test/
The "fullscreen tool/icon" is missing on the video.  When I put the url of the video in the browser the fullscreen option is visible.  Am I missing something?
On your demo page, unfortuantely there is no vimeo button , so I couldn't test it there.

**Comment by cbopp-art** [comment]
Hi,
If you embed a vimeo video, fullscreen basically would be disabled by default.
So add the option ```allowfullscreen``` to the iframe options, this would be passed 1:1 to the iframe tag.
```javascript
$('#myvimeo').lightcase({
	iframe: {
		allowfullscreen: 1
	}
});
```

**Comment by SpabRice** [comment]
I knew it will be something simple I was missing.
Thanks.

**Comment by espinh0** [comment]
sorry i tried a lot but i didnt get it. were i should put this code? where i can get my video ID to call it? im noob, i need it clearly
```
$('#myvimeo').lightcase({
    iframe: {
        allowfullscreen: 1
    }
});
```
