### ISSUE TITLE
v2.3.4 issue with Chrome 49.0.2623.75

### ISSUE THREAD

**Issue by sdfereday** [cbopp-art/lightcase#57]
Seems to be an issue where images aren't being swapped when the URL of the <img /> tag changes on selection of next or previous buttons. Can override or resolve when adding a random param after the <img /> tag url, eg:

`src="/media/1028/lobby.jpg?2312"`

**Comment by Gourmentt** [comment]
Double that
`$(window).resize()` after load another image can help too as workaround

**Comment by karatechops** [comment]
I had to take it one step further and add a url parameter to the href in the thumbnail.

Here's the thumbnail...
```
<a href="img/my_pic.jpg?123" data-rel="lightcase:myCollection"><img class="img-responsive-gall" src="img/my_pic_thumb.jpg"></a>
```

and the image tag..
```
<img id="gall-1" src="img/my_pic.jpg?123">
```

**Comment by viitek** [comment]
for me neither of suggested workarounds works. Images still don't swap .. sometimes .. most of the time but not always .. The description and counters change as supposed to, only the image stays the same ... tested on multiple computers and version of Chrome and Chromium

**Comment by karatechops** [comment]
It seems to be a Chrome bug as I've run into this with a few other animation heavy projects not using Lightcase. Divs wont redraw when their content changes, I've reported the bug to Google - hopefully they get a fix rolled out. In the mean time what these fixes are accomplishing is forcing the browser to re-render the div, anyway you can find to do that should theoretically work. You could also try tapping into GPU rendering with something like - 
.lightcase-contentInner {
    transform: translateZ(0);
}

**Comment by schfkt** [comment]
> I've reported the bug to Google - hopefully they get a fix rolled out

@karatechops can you post here a link to the issue in Chrome's bug tracker?

**Comment by cbopp-art** [comment]
I think chrome has been fixed in the meantime, right?

**Comment by viitek** [comment]
seems so, osx 10.11.4, Chrome 50.0.2661.75, but not Chromium 51.0.2683.0 .. weird
