### ISSUE TITLE
starting lightcase without link

### ISSUE THREAD

**Issue by quma** [cbopp-art/lightcase#58]
Hallo,

how I can start lightcase from a ajax success event like:

```
if (json['success']) {
		lightcase.start({
  				alert('hello!');
		});
```

thx

**Comment by cbopp-art** [comment]
Hi!
Take a look at the very last example of the [demo page](http://cornel.bopp-art.com/lightcase/#demo) 'On the fly' and read the section about [hooks](http://cornel.bopp-art.com/lightcase/documentation/#hooks).

A fully working example can be found for element #various9 at the end of the initialization file.
http://cornel.bopp-art.com/lightcase/project/js/lightcase.init.js

Hope this does help you!

**Comment by quma** [comment]
thanks !

**Comment by cbopp-art** [comment]
Can I close this issue? Did it help for you?
Thanks for your short reply!

**Comment by quma** [comment]
yes, thank you this solve my problem
