### ISSUE TITLE
Scrollable image/content that´s higher then the viewport

### ISSUE THREAD

**Issue by JensNielsen81** [cbopp-art/lightcase#59]
First, thanks for an awesome lightbox.

I am trying to use your plugin on my portfolio, for showcasing full pages in the lightbox.

I´m using forceHeight: true and maxWidth: '1366px' to make sure the image is the size i want.
But the problem is that the images are very high and center in the screen(http://thinkbear.net/stuff/lightcase-centret-image.png).

How would i go about making the image scrollable and not centeret?

Best regards 
Jens

**Comment by cbopp-art** [comment]
Hi!
May you could force the type to ```iframe``` instead of the type which is automatically detected by lightcase according to the file suffix.

http://cornel.bopp-art.com/lightcase/documentation/#property-type

**Comment by JensNielsen81** [comment]
Hmm nice idea, but I cant controll the height, it will only go up to 500px.
Plus, i cant controll the image width, so it wont work on mobile ect.

**Comment by cbopp-art** [comment]
try, this should work:
```
.lightcase-open body {
  overflow: hidden;
}
#lightcase-case {
  overflow-y: auto;
}
```

**Comment by stebogit** [comment]
@cbopp-art don't know if @JensNielsen81 solved his issue, but I'm having the same problem, although on mobile works great.
I'm using an `inline` lightcase for showing an image with a blurb of text underneath, and the text might be quite long:

```html
<a class="grouped" data-rel="lightcase:maps:slideshow" href="#id1">
    <img src="/path/to/small.jpg" alt="small photo">
</a>

<div id="id1" style="display: none;">
    <h2 class="modal-week-title">Title</h2>
    <img src="/path/to/big.jpg" alt="big photo">
    <div class="description">
        <p>Some big blurb...</p>
    </div>
</div>
```

For anybody who might encounter the same issue, I fixed it adding this:
```css
.lightcase-open body { overflow: hidden; }

#lightcase-case {
    position: fixed !important;
    max-width: 800px !important;
    width: 90% !important;
    height: 95% !important;
    overflow: auto !important;
}
```
copying it from the mobile setup.
My js options:
```js
$('a[data-rel^="lightcase:maps:slideshow"]').lightcase({
    slideshowAutoStart: false,
    showSequenceInfo: false,
    swipe: isMobile,
    transition: 'fade',
    speedIn: 50,
    disableShrink: true,
    speedOut: 50,
    maxHeight: h * .95,
    maxWidth: w * .95 + 'px',
    timeout: 2000,
    fullscreenModeForMobile: true,
});
```
@cbopp-art it might be useful to have this behavior maybe as an `option`, allowing lightcaso to easily show any content.
