### ISSUE TITLE
Iframe duplicates itself on Lightcase Close

### ISSUE THREAD

**Issue by CodeWolfSeven** [cbopp-art/lightcase#60]
I am using Lightcase.js on a barebones custom site install.  I am using Donate.ly as a donations platform.  They provide an inline script to run wherever I want the form to populate.  This script generates an iframe.  Everything appeared to be working fine, however, upon usage and inspection, every time I close my lightcase lightbox, the iframe replicates itself.  In the example screenshots below, only 1 instance of the iframes loads initially.  Then, after opening and closing twice, you can see I have 3 instances of the iframe.

![screen shot 2016-04-09 at 8 41 58 pm](https://cloud.githubusercontent.com/assets/17693193/14407351/92415e40-fe93-11e5-95a6-5fae2bcb57e5.png)

![screen shot 2016-04-09 at 8 41 37 pm](https://cloud.githubusercontent.com/assets/17693193/14407354/997a0054-fe93-11e5-9b21-0343a5fd70de.png)

_**One Iframe Loaded in = 1 donation form *_*

![screen shot 2016-04-09 at 8 41 00 pm](https://cloud.githubusercontent.com/assets/17693193/14407355/9ef4659c-fe93-11e5-90d7-5f4f3e2d24f1.png)

_**After a close and re-open, Another donation form follows the first *_*

![screen shot 2016-04-09 at 8 41 15 pm](https://cloud.githubusercontent.com/assets/17693193/14407356/a1da73aa-fe93-11e5-8007-e4322415a0ba.png)

This does not happen with Magnific lightbox, but I really want to use lightcase because it rocks.  A workaround would be much appreciated!

Thanks!

**Comment by cbopp-art** [comment]
Just with the screenshots it is not possible to reproduce that error.
Could you provide me a demo link or something?

Thanks.

**Comment by cbopp-art** [comment]
Could you figure out the issue? Can we close this one?

**Comment by CodeWolfSeven** [comment]
I wasn't able to figure it out. I ended up abandoning the lightbox idea :)

**Comment by cbopp-art** [comment]
Ok. Thanks for your response!
