### ISSUE TITLE
Uninitialize plugin / filtering items

### ISSUE THREAD

**Issue by schovi** [cbopp-art/lightcase#61]
Hi,

we are faced to problem, where we filter our gallery. Filtering is made simple with hiding of some photos. Filtering is based on some category slug. Each photo can have multiple categories. We tried to use data-lc-categories, but with fact that one photo can have multiple categories and we filter just one category result is follow: Visible are just 2 photos, but lightcase is applies to all photos which have similiar category as origin one even if they are not visible.

Our idea how to hack this was to remove `data-rel="lightcase"` and reinitialize lightcase only on visible photos, but it totally breaks everything :)

Best solution will be if we can "unapply" lightcase plugin, but it is not possible with current API. Maybe give us hint, how to do by ourself :)

**Comment by cbopp-art** [comment]
Could you might use something like ```$('data-rel^=lightcase').unbind().removeData();```?

**Comment by cbopp-art** [comment]
@schovi Did you found a working solution for this?

**Comment by schovi** [comment]
@cbopp-art It is really long time ago. I guess we hacked it somehow :)

**Comment by cbopp-art** [comment]
Ok, so i'm going to close this issue. Thanks!
