### ISSUE TITLE
Prev & Next

### ISSUE THREAD

**Issue by sevasargsyan** [cbopp-art/lightcase#62]
Hi. How to make Prev & Next ? http://prntscr.com/asx2r9
my code
`jQuery(document).ready(function($) {
    $('a[data-rel^=lightcase-product]').lightcase({
        showTitle: false,
        transition: 'scrollHorizontal',
        //classPrefix: 'lightcase-test',
        slideshow: true
    });
});`

**Comment by cbopp-art** [comment]
Hi!
Prev/Next appear per default as if you have more than one item within a collection.
http://cornel.bopp-art.com/lightcase/documentation/#collections
