### ISSUE TITLE
Connecting / Binding multiple anchor tags for collections

### ISSUE THREAD

**Issue by SpabRice** [cbopp-art/lightcase#63]
It's more a feature request than an issue, unless it might already exist and I don't know it.

Case:
I have multiple items which opens a lightcase object with "collection" (next/prev).
Now, each of these items have 2 different anchor tags (one with an image and one with a name). 

Example:
`<a href="image1.jpg" data-rel="lightcase:myCollection"><img src="thumb.jpg"></a>`
`<h4><a href="image1.jpg" data-rel="lightcase:myCollection">Preject Name</a></h4>`

The plugin is indentifying these 2 anchors as individual.  So if I click the on the thumb it opens the image1.jpg and if I click 'next' the image1.jpg is opened again comming from the h4 anchor.
It's kind of normal, but is there a possibility to "connect" or "bind" these 2 anchors so the script can identify them as one?

PS: I know it's possible to wrapp the image and h4 into 1 anchor tag via html, but it's not the way I want to go.

**Comment by cbopp-art** [comment]
Not possible per default. But why do you bind both links to lightcase?
One of those links could simply serve as a trigger of the other.
