### ISSUE TITLE
Click on image

### ISSUE THREAD

**Issue by TiagoDeSousa** [cbopp-art/lightcase#64]
Is it possible to click on an image and move to the next one?
Thanks!

**Comment by cbopp-art** [comment]
Yes, just bind a click-event to your image and trigger the next button.

**Comment by TiagoDeSousa** [comment]
Sorry I don't really know how to do that my JS skills are very limited :(

**Comment by cbopp-art** [comment]
@TiagoDeSousa Can we close this?

**Comment by TiagoDeSousa** [comment]
I actually didn't quite manage to do it as mi js skills are very limited.

**Comment by cbopp-art** [comment]
@TiagoDeSousa I hope you could manage to solve it somehow.
