### ISSUE TITLE
How to stop auto play

### ISSUE THREAD

**Issue by TiagoDeSousa** [cbopp-art/lightcase#65]
By default lightcase auto rotates images how can I stop that from default? Is there also an option to disable the play/pause button too?
Thank you.

**Comment by cbopp-art** [comment]
Have you seen the option navigateEndless? (default value is ```true```)
http://cornel.bopp-art.com/lightcase/documentation/#property-navigateEndless

You can disable play/pause button if you set option ```slideshow``` to false and/or remove ```:slideshow``` at the end of your ```data-rel``` attribute value for items.

**Comment by cbopp-art** [comment]
@TiagoDeSousa Did you found a solution? Can we close this issue?
Thanks.

**Comment by TiagoDeSousa** [comment]
Yes thank you so much!
