### ISSUE TITLE
Pass data variable to ajax call

### ISSUE THREAD

**Issue by rjpedrosa** [cbopp-art/lightcase#66]
Hi,

How to I pass a data attribute to the ajax call?

Tried this but not working:

`type: 'ajax',
ajax: {
width : 'auto',
height : 'auto',
type : 'get',
dataType : 'html',
data : {
    video_id: $(this).data("videoid")
    }
}`

Any help?

(by the way it works fine when I hard-code a video ID, so the problem is making it dynamic)

Thanks

**Comment by cbopp-art** [comment]
Hi!
Pass data within a variable you define before.
May the following closed issue can help you:
https://github.com/cbopp-art/lightcase/issues/32

**Comment by rjpedrosa** [comment]
Hi,

Tried this, doesn't work:

`$('a[data-rel^=lightcase]').lightcase({
	onStart: {
		setAjaxRequestData: function () {
			lightcase.settings.ajax.data = {video_id: $(this).data('videoid')};
		}
	},
	maxWidth: 1140,
	onCleanup: {
		remove_contents: function() {
			$(".video-lightbox-contents").empty();
		}
	},
	type: 'ajax',
	ajax: {
		width : 'auto',
		height : 'auto',
		type : 'get',
		dataType : 'html'
	}
});`

The issue you mentioned is too long, not sure what to do.
Any help on what exactly should I do?

Thanks!

**Comment by rjpedrosa** [comment]
Think I got it. This seems to work fine:

    $("a.video-large").unbind('click.lightcase').click(function(event) {
		
        event.preventDefault();
        var video_div = $(this).data("videodiv");
        var videoid = $(this).data("videoid");
        
        $.get("<?php echo get_stylesheet_directory_uri(); ?>/inc/video-lightbox.php", {
            video_id: videoid
        })
        .done(function( data ) {
            $(video_div).html(data).hide();
            lightcase.start({
                href: video_div,
                maxWidth: 1140,
                onCleanup: {
                    remove_contents: function() {
                        $(".video-lightbox-contents").empty();
                    }
                }
            });
        })
        .fail(function() {
            alert("Failed to load the video");
        });    
    });

**Comment by rjpedrosa** [comment]
But I would still want to use your ajax property.
Where do I put the url?

**Comment by cbopp-art** [comment]
What are you returning with the ajax response? An URL, HTML?

**Comment by rjpedrosa** [comment]
HTML.

Basically I have a list of videos. For each one I am creating an empty div which will hold the content for the lightbox. I could populate that div when listing the videos, but then the page takes ages to load. I want it to be populated only when people click on the video link, by ajax.
Ajax call is made to a PHP file that accepts a POST var with the video id, so it knows which video to load. That why I need to pass a variable withing the ajax call.

**Comment by rjpedrosa** [comment]
The code in the comment I've made 20 hours ago works. The problem is it takes 2 or 3 seconds between the click and the lightbox poping up. I would prefer for the lightbox to pop up immediately and showing the loading icon until the ajax call has completed.

**Comment by rjpedrosa** [comment]
Here's the page, so you can see the code: [http://interelgroup.com/interel-tv/](http://interelgroup.com/interel-tv/)

**Comment by cbopp-art** [comment]
Your first example basically should work, too. But mind that you need to use POST as request type as long as you want to pass any data along with the request.
So, switching your request type from ```GET``` to ```POST``` should be sufficient.

**Comment by rjpedrosa** [comment]
OK.
But where do I put the URL of the request?

**Comment by rjpedrosa** [comment]
This might also help you better understand: [https://db.tt/SLMtZ0xI](https://db.tt/SLMtZ0xI)

**Comment by cbopp-art** [comment]
You can put the url into the ```data-lc-href``` or ```href```attribute of your link and setting the option ```'type': 'ajax'```

using the option 'href' to force your url target is also possible.
http://cornel.bopp-art.com/lightcase/documentation/#property-href

**Comment by rjpedrosa** [comment]
Did it but still linking to the php file rather than opening the lightbox.

    $('a.video-trigger').lightcase({
            maxWidth: 1140,
            onCleanup: {
                remove_contents: function() {
                    $(".video-lightbox-contents").empty();
                }
            },
            type: 'ajax',
            ajax: {
                width : 'auto',
                height : 'auto',
                type : 'post',
                dataType : 'html',
                data : {}
            }
        });
    });

and 

`<a class="video-trigger" data-videoid="<?php echo $video->ID; ?>" data-videodiv="#video-<?php echo $video->ID; ?>" href="<?php echo get_stylesheet_directory_uri(); ?>/inc/video-lightbox.php?videoid=<?php echo $video->ID; ?>">`

**Comment by rjpedrosa** [comment]
Sorry, there were some extra brackets on my code. Now lightbox loads, but empty.
Note: I am passing the video ID variable with the ajax request url itself (as a get parameter), rather than passing as an ajax request variable.

**Comment by rjpedrosa** [comment]
Never mind, was another typo. Finally got it! :)
Many thanks for your patience!

Still think it would be good to make it more clear in the documentation how to use the ajax property.

**Comment by cbopp-art** [comment]
Ok, do you have a suggestion what is missing or unclear in the documentation?
Thanks

Btw: Did you also check the examples with code in lightcase.init.js?

**Comment by rjpedrosa** [comment]
You can add something like "The Ajax url should be set as the data-lc-href or href attribute".
Also, as I couldn't find a way to pass POST ajax variables read from data attributes, might be easier to use GET instead and pass the variables within the request url itself, like `request.php?foo=xxxxx`, as I did.
Might worth telling people that too. Or explain (if it is even possible), how to pass dynamic variables to the data property of the ajax call.

Regarding examples in lightcase.init.js, not sure what you mean.
