### ISSUE TITLE
Ajax form exemple

### ISSUE THREAD

**Issue by Champi57** [cbopp-art/lightcase#67]
Hi, could u give me an exemple of a send.php that would work with ligthcase?

I am not familiar with Ajax but want to use a lightcase form on a website.
`<form id="ajax-form" name="ajax-form" action="/lightcase/view/send.php" method="post" data-rel="lightcase"><ul class="input-list">
				<li><input type="text" id="name" name="name" placeholder="Your nickname" value="" required></li>
				<li><input type="submit" name="submit" class="button blue" value="Submit"></li>
			</ul>
		</form>`

**Comment by cbopp-art** [comment]
Hi!
Just check the [initialisation file](http://cornel.bopp-art.com/lightcase/project/js/lightcase.init.js) and example #various2

On php side you would need to validate and return rendered data as HTML or maybe JSON, depending on your custom needs. The example I mentioned before is using HTML format for response.

**Comment by Champi57** [comment]
Yeah thx i managed it and it works fine :)
