### ISSUE TITLE
Pass Html To Display To Lightcase

### ISSUE THREAD

**Issue by YodasMyDad** [cbopp-art/lightcase#68]
I have an Ajax call which is returning a chunk of Html which I need to display in a lightcase window

I have the following in my success method on my Ajax call:

```
var result = "THIS IS MY HTML VARIABLE"; 
lightcase.start({ 
href: '#', 
onFinish: { 
    baz: function () { 
    // How do I get result into lightcase here?  
    lightcase.resize(); 
        } 
    } 
});
```

I wanted to be able to something like a .html(result) to push the html into Lightcase?

**Comment by cbopp-art** [comment]
Hi @YodasMyDad
Try ```lightcase.get('contentInner').html(result);```

**Comment by cbopp-art** [comment]
@YodasMyDad Can we close this?
