### ISSUE TITLE
Video fallbacks

### ISSUE THREAD

**Issue by Quaked** [cbopp-art/lightcase#69]
Using a href directly to a mp4 works splendidly. It opens the video without a container and it looks as expected! However I'm not able to supply a WebM or OGG fallback? So then I created a hidden `<div id="video">` with the `<video>` tag and basically opened it with lightcase. This "worked" but doesn't give anywhere near the same experience as referencing the video file directly (I get a box and within the box there's a video).

Any idea how I can use mp4, webm and ogg? 
Maybe add it so `href="...mp4" data-src="...webm, ...ogg"` ?

**Comment by cbopp-art** [comment]
May you want to use a video player with fallback support like e.g. https://html5media.info
For instance this should work:
```
$('#myLink').lightcase({
    onStart : function() {
	html5media();
    }
});
```

**Comment by Quaked** [comment]
I'm not talking about support for the ```<video>``` tag, I'm talking about a fallback for MP4-format. It's recommended that you don't solely depend on an MP4 working on all browsers on all devices, hence you provide another ```<source>``` with a WebM format, and if you want to cover all grounds a OGG as well.

Your code needs to be modified for this purpose as simply just having a video in MP4-format will not work on all devices. Fallbacks must be provided. This is how you'd normally implement a video:
```HTML
<video id="video" controls poster="bunny.jpg">
	<source src="big_buck_bunny.mp4" type="video/mp4">
	<source src="big_buck_bunny.webm" type="video/webm">
	<source src="big_buck_bunny.ogv" type="video/ogg">
	<p>Your browser does not support video playback.</p>
</video>
```

Now how do I get that to function in lightcase? I'd love to be able to use the id ```#video``` and hook up lightcase, but that gives an ugly "box" around, not as smooth and good-looking as supplying "big_buck_bunny.mp4" as ```href``` - but using the latter I don't have support for WebM or OGV (OGG) if MP4 isn't supported by the browser.

**Comment by cbopp-art** [comment]
Ok, I can see the problem. Implementation of the possibility to add multiple video sources or formats respectively will be a simple thing more or less. I simply would prefer a new ```data-lc-``` attribute similar to the categories where all different formats can be defined and each will be added into the ```<video>``` tag then.

Will do that!

**Comment by cbopp-art** [comment]
Hi @Quaked 
As a new feature it is possible now to just pass multiple urls with different video formats as comma separated string via tag attribute `data-lc-href` and lightcase would take care for the rest. This means, lightcase is checking, which format that is most supported by the browser.

Example:
```
data-lc-href="/lightcase/project/videos/animals.mp4, /lightcase/project/videos/animals.woff"
```

I would appreciate a lot if you could test this change extensively, too!

Thanks again for having shared your ideas and of course, having created that issue.
