### ISSUE TITLE
Safari 5.1.7 and IE 11.0.31 Don't like the Script

### ISSUE THREAD

**Issue by dwmclean** [cbopp-art/lightcase#70]
I cannot comment how wonderful your plugin is or the many uses that can be built on your platform.

I have modified some of the script from the lightcase.init.js to run some cool looking modals (on the fly) and an occasional image. Works wonderful in Opera, Chrome, and Firefox. 

IE and Safari...not so much. I know it is a more global thing since I went to your demo page, and the same issues happened (it wasn't me monkeying with the script on my local tester.) Didn't know if this is known, cared about, or in the works. Regardless, I think it is time to put some currency in the PayPal for you.

**Comment by cbopp-art** [comment]
Hi!
First of all, thank you for the compliments. I'm very glad to hear that people like it that much, also its flexibility and extensibility.
What issue exactly have you faced in IE/Safari? Could you provide some more infos about like screenshot, demo or similar?

Thanks in advance!
Cornel

**Comment by dwmclean** [comment]
When an image is selected on screen, when clicked, it opens the image as if there was no lightbox on a separate screen as if it were a regular (default) picture. Same with the videos. You have to use the back button on the browser to go back to the page. 

![iepictures](https://cloud.githubusercontent.com/assets/19414913/15356874/6903f5f2-1cc9-11e6-893e-00379bfae548.jpg)

When I go into the debug, "Navigation occurred"

The "On the Fly" Link and the Google Map on the demo are returning to the top of the screen like a <a href="#"> without ever launching the lightbox.

![ieerror](https://cloud.githubusercontent.com/assets/19414913/15356788/efb0522c-1cc8-11e6-9c31-79957f61acfa.jpg)

**Comment by cbopp-art** [comment]
Thank you for reporting. Has been fixed now!
