### ISSUE TITLE
Google map displays badly on mobile when previously open

### ISSUE THREAD

**Issue by qcaron** [cbopp-art/lightcase#71]
The title is self-explanatory. 

Could not investigate this further since it is my first use. It displays correctly on computer screen after initial display.

**Comment by JVesth** [comment]
I have the exact same problem. I think it has to do with the `var center = myGoogleMap.getCenter();` line in the lightcase.init.js file.

It does not center correctly, on mobile (android), after it has been opened once.

Chrome console throws this error: 
> lightcase.init.js:41 Uncaught TypeError: myGoogleMap.getCenter is not a function

**Comment by qcaron** [comment]
Probably meaning _myGoogleMap_ is destroyed at some point for mobiles... I will try to make this right and keep you posted.

**Comment by JVesth** [comment]
Thank you, qcaron. I hope you find a solution.

cbopp-art stil active in here?

**Comment by cbopp-art** [comment]
@JVesth I'm still active here, yes. But I also appreciate to have some of you as well investigating and helping here to solve that issue, because my time is rare currently.

**Comment by JVesth** [comment]
@cbopp-art, I completely understand your approach.

I have been trying to fix this myself, on and off as work permits, but sadly I haven't been able to solve it myself.
I'm at a crossroad now where I either need some expert help or have to implement some other lightbox solution. The latter I really don't want to do since I have enjoyed working with lightcase so far.

**Comment by cbopp-art** [comment]
There is a solution. Important is, that also the google map gets resized as well not only the lightcase element.

Here is a working example:
```javascript
var myGoogleMap = null;

$('#various8').lightcase({
  onFinish: {
    // Call a new function after lightcase processing has finished
    // to initialize the map canvas, set markers and so on...
    initializeGoogleMap: function () {
      var mapOptions = {
        zoom: 3,
        center: new google.maps.LatLng(46.8333, 8.3333)
      };

      myGoogleMap = new google.maps.Map(
        $('.lightcase-inlineWrap').get(0),
        mapOptions
      );

      // Optional but recommended:
      // Add on resize listener for better responsiveness
      google.maps.event.addDomListener(window, 'resize', function () {
        google.maps.event.trigger(myGoogleMap, 'resize');
        myGoogleMap.setCenter(myGoogleMap.getCenter()); 
      });
    },

    // We need to handle the map dimensions like dimensions of
    // an image, so that's why we change data-type manually here!
    changeType: function () {
      lightcase.get('case').attr('data-lc-type', 'image');
    },

    // We just trigger a resize here so that lightcase will
    // recalculate the dimensions automatically
    reCalculateDimensions: function () {
      lightcase.resize();
      google.maps.event.trigger(myGoogleMap, 'resize');
    }
  },
  onCleanup: {
    removeListener: function () {
      google.maps.event.removeListener(myGoogleMap);
    }
  }
});
```

**Comment by cbopp-art** [comment]
@qcaron And again, thanks a lot for having faced this issue!

**Comment by cbopp-art** [comment]
Did it work for you? Can we close this one?
