### ISSUE TITLE
Scrolling background when lightcase active

### ISSUE THREAD

**Issue by EdaCZ** [cbopp-art/lightcase#72]
Hi. Thank you for this great lightbox.

There is one small issue. When you open lightcase overlay a then scroll with mousewheel, background is crolling, which is not wanted.

It should fix scroll position of background as other lightboxes do.

**Comment by marlonleite** [comment]
try it:

`onStart: {
					bar: function () {
							$('body').css('overflow', 'hidden');
					}
				},
				onClose: {
					bar: function () {
							$('body').css('overflow', 'auto');
					}
				}`

**Comment by cbopp-art** [comment]
There is a simple trick.

```
.lightcase-open body {
  overflow: hidden;
}
#lightcase-case {
  overflow-y: auto;
}
```
