### ISSUE TITLE
Prev/Next display as squares on other computers. 

### ISSUE THREAD

**Issue by mieradi** [cbopp-art/lightcase#73]
I've noticed this on two other computers. Any support on this?

**Comment by nickpish** [comment]
For the UI elements, make sure you have the necessary font files (i.e. lightcase eot/svg/ttf/woff) linked properly in your CSS-- otherwise, they won't load and empty characters will display in their place.

**Comment by cbopp-art** [comment]
This has to be an issue with your implementation actually. Basically fonts are working well.
