### ISSUE TITLE
Fit fluid image in inline window?

### ISSUE THREAD

**Issue by nickpish** [cbopp-art/lightcase#74]
Hi, first off, I want to say thank you for such a phenomenal plugin-- I reviewed many (many) lightbox plugins for use in my portfolio, and this one is far and away the best I've encountered.

As for my question-- which is admittedly more CSS-related-- I'm using Lightcase for displaying inline elements, and I'm trying to get large images within to scale proportionally to fit the window. I'm using `max-width:100%` and `max-height:100%` on images contained within the boxes, and while the width scales properly, taller images do not fit the window height, and therefore cause a scrollbar to appear if the height exceeds that of the window. I have tried every method I can think of, including using the `object-fit` property, but to no avail. If I explicitly set a height to the inline window container, the image will scale properly, but I want it to be responsive and just fit the size as defined in the Lightcase settings (i.e. `maxWidth` and `maxHeight`).

Any ideas here on how to get the image to properly fit the height of the popup window, without explicitly defining a height for the container? Thanks very much for any assistance here.

**Comment by cbopp-art** [comment]
Hi @nickpish I don't know if I understand correctly, but why do you open images with type `inline`? Couldn't you just open the image so that lightcase identifies it as an image:
`<a href="my/path/to/image.jpg" data-rel="lightcase">...</a>`

Could you provide me a screenshot or demo page?

**Comment by nickpish** [comment]
Hi @cbopp-art, thank you for your response. I'm using your plugin on my portfolio site-- in conjunction with an Isotope/Masonry grid-- and my initial reasoning for wanting to use an inline type is so that I could include more information, i.e. markup, for a given portfolio element. That is-- I could display a larger image version of a given thumbnail in the grid, and display additional information for that particular portfolio item in the lightbox-- a rich caption, if you will.

However, as I've spent more time with the design and exploring the Lightcase options, I'm thinking it would make more sense to just use the image type as you mentioned-- I'm wondering, however, if it's possible to inject custom markup into a caption element underneath the image in the Lightbox? I'm attaching a basic mockup here of what would be ideal-- thus, modifying Lightcase to display a custom caption from markup defined in a hidden element. (I'm also attaching a screengrab illustrating my earlier question about adapting image height.)

 Thanks again for any assistance here-- the ability to use collections and categories is amazing!

![lightcase-screengrab](https://cloud.githubusercontent.com/assets/4361220/16638982/7cb35e00-43a0-11e6-8dd7-bb94bb60cce9.png)
![lightcase-caption-mockup](https://cloud.githubusercontent.com/assets/4361220/16638991/87c065ae-43a0-11e6-9632-a90d20c82403.png)

**Comment by cbopp-art** [comment]
Yes, it is possible to add a rich caption if you make use of the hook feature (e.g. onFinish) and fill the caption element with the content.

**Comment by cbopp-art** [comment]
then, make sure that your caption is not position:absolute but relative so that lightcase calculates it into the total height and resizes the image above accordingly.

then simply call:
lightcase.resize()

**Comment by nickpish** [comment]
Thanks for your response @cbopp-art , it's most appreciated. So, if I have a series of grid items that each launch a lightbox like so: `<div class="grid-item"><a href="#" data-rel="lightcase">grid item</a></div>` and within each of those grid items I have a caption `div` (say with a `capInfo` class) that is hidden by default, could I use something like the following in the Lightcase initialization: 
```
$('a[data-rel=lightcase]').lightcase({
	onFinish : {
		function() { 
			var caption = $(.capInfo).html();
			$(#lightcase-caption).html(caption);
			lightcase.resize();
		}
	}
});

```

**Comment by cbopp-art** [comment]
There are some correction to do so far that it would work:
1. The hook function needs a key name.
2. use $(this).find('.capInfo').html()
3. use lightcase.get('caption')

I'm sorry but i cannot use javascript code markdown because i'm writing from mobile.

**Comment by nickpish** [comment]
Hi @cbopp-art thanks for your continued support-- I've been unable to get the caption to display in this way, so I've set up a jsfiddle [here](https://jsfiddle.net/nickpish/7qudm0my/) (which I will leave in place for others who might desire a similar customization.) I've given the hook function a key name, and called `lightcase.get('caption')` but to no avail. Assuming I'm leaving out something obvious here? Thanks again.

**Comment by cbopp-art** [comment]
You're very welcome!

I mean in this way (untested):
```javascript
jQuery(document).ready(function($) {
  $('a[data-rel^=lightcase]').lightcase({
    onFinish: {
      custom: function() {
        var caption = $(this).find('.capInfo');
        if (caption.lentgh) {
          lightcase.get('caption').html(caption.html());
        }
        lightcase.resize();
      }
    }
  });
});
```

**Comment by nickpish** [comment]
@cbopp-art ok, I've updated the fiddle [here](https://jsfiddle.net/nickpish/7qudm0my/), and on inspection, it doesn't look like lightcase is getting the content-- should we be explicitly injecting it into `#lightcase-caption` and forcing it to `display:block`?

**Comment by cbopp-art** [comment]
Oh yes, sorry! Actually you need to take the right selector for the caption in lightcase. And make it visible then via .show() or define a default dummy caption via option so that lightcase expect that there is a caption to display.

**Comment by nickpish** [comment]
Hi @cbopp-art yes, that was the final necessary piece-- I've updated [the fiddle](https://jsfiddle.net/nickpish/7qudm0my/) for future reference and here is the working initialization (please let me know if you see any potential issues with the syntax.) Thanks again, this is great!

```
jQuery(document).ready(function($) {
  $('a[data-rel^=lightcase]').lightcase({
        onFinish : {
            custom: function() {
                var caption = $(this).find('.caption');
                if (caption.length) {
                    lightcase.get('caption').html(caption.html());
                    $('#lightcase-caption').show();
                } 
                lightcase.resize();
            }
        }
    });
});
```

**Comment by nickpish** [comment]
One final question-- I've got the custom captions working well using the code above, but I would like to be able to show links within the captions, and given that I can't define one anchor inside of another-- i.e. within the one to launch Lightcase itself-- I'm trying to use a `data-href` attribute within the caption markup, like so
```
<div class="lc-caption">
     <p class="cap-link" data-href="http://website.com">View website</p>
</div>
```
I then have a click function for `.cap-link` to use the `data-href` value to jump to the relevant site, but it doesn't seem to be working; is there something within Lightcase that would be disabling link behavior within the lightbox and if so, is there a way to circumvent this?

**Comment by nickpish** [comment]
I actually just figured it out-- in case anyone stumbles upon this thread and would like to add custom rich captions with links, make sure to delegate the click event; in this way, for example:
```
$(document).on('click', '.cap-link', function () {
        window.location.href = $('.cap-link').attr("data-href");
        return false; 
});
```
Thanks again @cbopp-art for your support; this plugin is fantastic.

**Comment by cbopp-art** [comment]
No, there is nothing preventing from lightcase. Great that you could figure out a solution that works for you.

**Comment by cbopp-art** [comment]
@nickpish Can we close this issue?

**Comment by nickpish** [comment]
Yes I'll close! Thanks again for all the help.
