### ISSUE TITLE
Source set question

### ISSUE THREAD

**Issue by nickpish** [cbopp-art/lightcase#75]
I love the integration of source sets for responsive images, and I just want to be clear on one point: the docs reference the following example:

`<a href="" data-lc-href="path/to/media1_small.jpg, path/to/media1_large.jpg 2x" data-rel="lightcase">Your link description or thumb</a>`

I see that this is following the basic syntax of `srcset`, but can one set a default source in the `href` attribute as a fall-back, or must it be left blank to allow `data-lc-href` to work? Thanks!

**Comment by cbopp-art** [comment]
It can be left blank I think. But it depends on your integration of the plugin. For instance if you bypass the `init` function by just calling the  `start` function, the origin link event wouldn't be catched by lightcase.
Look at the `event.preventDefault()` in https://github.com/cbopp-art/lightcase/blob/master/src/js/lightcase.js#L31

**Comment by nickpish** [comment]
@cbopp-art ok, in my case I am using the typical initialization-- i.e. `$('a[data-rel^=lightcase]').lightcase();`-- so if I do include a default target in the case that JS is disabled, say:

    <a href="default-size.jpg" data-lc-href="medium.jpg 1.5x, large.jpg 2x">link target</a>

Would the other source set options behave as desired in the case that JS is enabled, and thus `event.preventDefault()` would kick in? (Hoping I'm understanding this correctly...)

**Comment by cbopp-art** [comment]
yes, in case that js is disabled the attribute href only would take effect then. but not in popup/lighgbox obviously.
