### ISSUE TITLE
Use lc-categories in conjunction with filters?

### ISSUE THREAD

**Issue by nickpish** [cbopp-art/lightcase#76]
I love the integration of categories in Lightcase to group content, and I'm wondering if there's a way to somehow combine this feature with the use of filters in [Isotope](http://isotope.metafizzy.co/). I found a couple other threads here related to the use of Isotope w/ Lightcase, but neither help in this respect. I'm using the following `click` function to filter image thumbnails that each trigger a Lightcase lightbox:

```
$('.filter-bar').on( 'click', 'button', function() {
        var filterValue = $(this).attr('data-filter');
        $container.isotope({ filter: filterValue });
});
```

I'm wondering if there's a way to also update the `data-lc-categories` value--i.e. with a corresponding `data-filter` value-- for the (visible) items that reflect the filtered category and thus hide the other items from the lightbox? Thus, clicking a "show all" button would either disable categories altogether, or make all thumbnails a single category. An alternative would be somehow forcing Lightcase to only show items from *visible* thumbnails. Thanks for any direction here!

**Comment by cbopp-art** [comment]
Does issue #35 may give the answer?

**Comment by nickpish** [comment]
Hi @cbopp-art I noticed that thread when searching, but not totally sure how to implement it-- would I need to completely re-initialize Lightcase with all relevant options within the `click` function above to disable `useCategories`, or is there a way I could somehow toggle that one option?

I was curious about the possibility of dynamically toggling the `data-lc-catetories` attribute itself, but not sure if that's possible... thanks again for your feedback!

**Comment by nickpish** [comment]
Hi @cbopp-art after researching a solution for a while, I have a different, more specific question for you: is there a way to save Lightcase's initialization options as a variable or in such a way that a property like `useCategories` could be saved and later overridden via, say, a click function like the above Isotope filter? I'm basically wondering if there's a way to change a property without having to re-initialize the plugin and all it's settings (like `maxWidth`, `maxHeight`, etc.)-- thus, somehow refer to the initial "state" of the plugin, override just a specific option (or set of options) and re-initialize?

**Comment by cbopp-art** [comment]
You could skip the `init` function and do the click binding directly by yourself and call the `start` function then. On the click event binding you read the data stored on the specific object.
Maybe something like this (untested):

```javascript
$('myLink).data('lightcaseOptions', {
    maxWidth: 300,
    maxHeight: 300
}).click(function () {
    lightcase.start($(this).data('lightcaseOptions'));
});
```

**Comment by nickpish** [comment]
Thanks @cbopp-art, so in this approach, if I'm understanding correctly, I wouldn't initialize the plugin in the typical way as in `$('a[data-rel^=lightcase]').lightcase();` but, rather, would invoke Lightcase with the options stored in `data` via `lightcase.start`?

**Comment by cbopp-art** [comment]
yes, exactly!

**Comment by nickpish** [comment]
@cbopp-art  Great, thanks! I also realized I could just save a default set of options as an object, initialize the plugin normally, and then use the `click` function along with jQuery's `extend()` method to override any relevant defaults in subsequent inits.

**Comment by cbopp-art** [comment]
@nickpish Can this issue getting closed?

**Comment by nickpish** [comment]
Yes, thanks again; hoping this thread might help someone down the road desiring a similar configuration!
