### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by elemis** [cbopp-art/lightcase#81]
Do we have to enter maxWidth and maxHeight values in the script? We'd like to display the images with their original size without entering any specific values. And if the images are bigger than the viewport, we'd like to have the images resized accordingly. What options do we need to use exactly?

**Comment by cbopp-art** [comment]
Finally, it is possible now use specific `width` and `height` now also in combination with `forceWidth` or/and `forceHeight`:

```
width: 1200,
height: 800,
forceWidth: true,
forceHeight: true
```

Check this issue #122 as well.
