### ISSUE TITLE
Turn off responsive layout?

### ISSUE THREAD

**Issue by schmelik** [cbopp-art/lightcase#82]
Is there an easy way to turn off browser responsive layout?
`@media screen and (max-width: 640px) { }`
in previous versions the css was separated and could be included or not.
now it looks like the css is built in one file.

thanks in advance

oh and at the moment I am not running SASS

**Comment by cbopp-art** [comment]
No, this is not possible. If you are using the compiled css file, you need to modify it and remove that part of css. Using the SASS source, you can just change the viewport breakpoint to 0 in the settings.

**Comment by cbopp-art** [comment]
@schmelik I would like to close this issue. Do you think the way I mentioned in my last comment is reasonable?

**Comment by cbopp-art** [comment]
@schmelik There is a separate compiled css file without breakpoint provided with the new version 2.4.0.
