### ISSUE TITLE
Alt caption doesn't work

### ISSUE THREAD

**Issue by SpabRice** [cbopp-art/lightcase#85]
Hello,

just trying to add and show the alt caption, but it doesn't work.
title="..." works fine but alt="..." displays nothing.  The option showCaption is set to true in js.
It only works if I add the caption via the js initialiser (caption: "test caption",) but this is not what I want.  I would like to have different texts for each image.

Am I missing somehting?

**Comment by cbopp-art** [comment]
Hi!
the attribute `alt` is for images only.

**Comment by cbopp-art** [comment]
Can we close this one?
You still can use the attribute data-lc-options on your link a tag and set the caption accordingl
