### ISSUE TITLE
Autoplay and YouTube videos

### ISSUE THREAD

**Issue by djmtype** [cbopp-art/lightcase#88]
The `autoplay` option doesn't seem to apply to YouTube videos. Is this intentional?

**Comment by cbopp-art** [comment]
Options for `video` are getting applied untouched to the HTML5 video tag which is created by lightcase. Actually, user can put in any option and they are beeing applied as arguments. Means, is not part of the lightcase plugin itself to check if they work or not.

In your case, Youtube is not provides as HTML5 video, but embedded as iframe or maybe flash?

**Comment by sashabeep** [comment]
To use autoplay you should just change type to ajax or iframe with adress
https://www.youtube.com/embed/[VIDEO_ID]?autoplay=1

**Comment by cbopp-art** [comment]
@djmtype I'm going to close this issue, it is not related to the plugin.
And thank you, anyways!
