### ISSUE TITLE
Issues with spaces in the filename

### ISSUE THREAD

**Issue by fvas-elearning** [cbopp-art/lightcase#89]
There is a major issue with spaces in the filename because of the "Source Sets" code. The parameters would be more conveniant if they where proper URL parameters, see the updated function below:

```
    /**
     * Normalizes an url and returns information about the resource path,
     * the viewport width as well as density if defined.
     *
     * I have changed this to use more standard URL syntax as the previous version brakes if there are
     * spaces in the file names.
     *   Current: data-lc-href="path/to/media2_default.jpg, path/to/media2_small.jpg 320w, path/to/media2_small_2x.jpg 320w 2x"
     *   NEW WAY: data-lc-href="path/to/media2_default.jpg, path/to/media2_small.jpg?w=320, path/to/media2_small_2x.jpg?w=320&x=2"
     *
     * @param  {string}  url  Path to resource in format of an url or srcset
     * @return  {object}
     */
    _normalizeUrl: function (url) {
      var srcExp = /^\d+$/;

      return url.split(/,[ ]?/).map(function (str) {
        var src = {
          width: 0,
          density: 0
        };

        src.url = str;
        var params = {};
        str.replace(/[?&]+([^=&]+)=([^&]*)/gi, function (str, key, value) {
            params[key] = value;
          }
        );

        if (typeof(params.w) !== 'undefined' && srcExp.test(params.w)) {
          src.width = parseInt(params.w);
        }
        if (typeof(params.h) !== 'undefined' && srcExp.test(params.h)) {
          src.height = parseInt(params.h);
        }
        if (typeof(params.x) !== 'undefined' && !isNaN(params.x)) {
          src.density = parseFloat(params.x);
        }
        return src;
      });
    },
```

**Comment by cbopp-art** [comment]
Hi @fvas-elearning 
Thank you for request. Why do you mean are url parameters more conveniant than the official src-set notation?

**Comment by fvas-elearning** [comment]
By having a urls in the format of: "path/to/media2_small.jpg 320w" you introduce a space into the url. What if a filename has a space like so: "path/to/media2 small.jpg 320w" then the algorithm fails.
But if you use a standard URL format it will work: "path/to/media2 small.jpg?w=320&x=2"

**Comment by cbopp-art** [comment]
You're actually right, the attribute `href` has to be a valid url string. Anyway, the src-set notation is only possible using the attribute `data-lc-href` which will be preferred of `href` by lightcase.

**Comment by EdaCZ** [comment]
I confirm this issue. I also had whitespace in filename (in attribute href) and it wasn't working.

As a workaround, I replaced whitespace by encoded "%20".

I will appreciate fix of this.
