### ISSUE TITLE
Moving from colorbox - need help

### ISSUE THREAD

**Issue by sashabeep** [cbopp-art/lightcase#9]
How to re-write my colorbox code to lightcase?
I'm using colorbox for some POST queries, for example, post form to colorbox

```javascript
function SendToFormBoxed(name,phone,email,idform,token,formzag){
        $.colorbox({
            //open: true,
            //scrolling: false,
            //innerWidth:'500',
            href:"post.php",
            data:{name:name,phone:phone,email:email,idform:idform,token:token,formzag:formzag},
            onComplete:function(){
                $.fn.colorbox.resize();
                //and other things...
            }
        });
    }
```
basic interest is post, and event when render finished (onComplete in colorbox)

**Comment by cbopp-art** [comment]
Hi Alex

As I understand, you don't have a physical link but you want to execute and
open lightcase on the fly and without any user interaction via javascript,
right?

There is no possibility yet to open lightcase without having an object
within the DOM.
Thus, I will take notice of that as a feature for one of the next releases.

Well, right now you can do it this way (as a trick):

$('<div data-href="post.php" data-rel="lightcase">').lightcase('start', {

typeMapping : {

ajax: 'php,<other,formats?>'

},
ajax: {

width: 500,

height: 'auto',

data: {

name: name,
phone: phone,
email: email,
idform: idform,
token: token,
formzag: formzag

},

onFinish: {

// called just before loaded data gets shown. So do something :)

}

}

});


Untested, but try it and call me back.
Hope I could help you!

Cornel

**Comment by sashabeep** [comment]
Will try in a couple days, not sure i trully understand what selector means.
In my case i use two php scripts - one for building form on the fly, and other to email, both work via post. 

Сoncretely function SendToFormBoxed used for posting already generated form from colorbox to colorbox

Not too easy to explain, for landing pages i need many forms with the same fields but different click-to action text above the form and on the submit button. I have many buttons with data-attributes which open forms:
```html
<a class="button buildform"
href="javascript:;"
data-index="0"<!--form template index defined in form.php--!>
data-idform="Parent block name for analytics"
data-formzag="Headline before the form"
data-formbut="Text on the button"
data-addtext="Additional text between headline and fields"
data-token="some сыка id in session">click to open a form</a>
```
Then i post this parameters to form.php to build form on the fly after click on this link
```javascript
$(".buildform").on("click",function(event){
        event.preventDefault();
        //pass to form placeholders
        var index = $(this).data("index");
        var idform = $(this).data("idform");
        var token = $(this).data("token");
        var formzag = $(this).data("formzag");
        var formbut = $(this).data("formbut");
        var addtext = $(this).data("addtext");
        
        $.colorbox({
            open: true,
            scrolling: false,
            innerWidth:'500',
            href:"form.php", //this script paste our text to placeholdres
            data:{index:index,idform:idform,token:token,formzag:formzag,formbut:formbut,addtext:addtext},
            onClosed:function(){
                //Do something on close.
            },
            
            onComplete:function(){
                //attach submit event to newly created form
                $("#colorbox form.modal").on("submit",function(event){
                    event.preventDefault();

                        var name = form.find("input[name='name']").val();
                        var phone = form.find("input[name='phone']").val();
                        var email = form.find("input[name='email']").val();
                        var idform = form.find("input[name='idform']").val();
                        var token = form.find("input[name='token']").val();
                        var formzag = form.find("input[name='formzag']").val();

                        SendToFormBoxed(name,phone,email,idform,token,formzag); //our function to post from colorbox to colorbox

                });
            }
        });
        
        return false;
    });
```

**Comment by sashabeep** [comment]
Tried this
```html
<a class="button buildform"
href="form.php"
data-index="0"
data-idform="Site header"
data-formzag="Order callback"
data-formbut="Please call me now"
data-addtext="Please fill your name and phone"
data-token="<?=$token;?>">Callback to me</a>
```
```javascript
$(".buildform").on("click", function(e) {
        $(this).toggleClass('buildform-clicked'); //doesnt work
        e.preventDefault();
    });
    
    
    $('.buildform').lightcase({
        type : 'ajax',
        ajax: {
            width: 500,
            height: 'auto',
            type: 'post',
            data: {
                index : $('.buildform-clicked').data("index"),
                idform : $('.buildform-clicked').data("idform"),
                token : $('.buildform-clicked').data("token"),
                formzag : $('.buildform-clicked').data("formzag"),
                formbut : $('.buildform-clicked').data("formbut"),
                addtext : $('.buildform-clicked').data("addtext")
            }
        },
        onFinish: {
        myFunction : function () {
            alert($('.buildform-clicked').data("index")); //still null
        }} 
    });
```
Still no effect. Lightcase started before active class applied to button
Trying to collect data-attributes from clicked link. Doesn't work
``$(this).data(something)``` also give undefined values in ```data{...}```

**Comment by cbopp-art** [comment]
Did you check out already that new example on the [lightcase demo page](http://cornel.bopp-art.com/lightcase/demo/#various2)?

**Comment by sashabeep** [comment]
Oh! Thanks for quick reply! Helpful example. Will try it now.
I think i just rewrite form builder to accept get parameters in link
But for further releases i request ability to open, resize and write to opened box

**Comment by sashabeep** [comment]
Just tried this! All that i need, Thanks a lot!
lightcase has any public function to close it? I just using a llittle delay and auto-close when form fuccesfully posted

**Comment by cbopp-art** [comment]
Yes, you can call this or within a certain timeout function and it will close your actual open lightcase:

lightcase.close();

**Comment by sashabeep** [comment]
Ugliest thing in my form builder on the fly via get - need to urlencode non-latin characters to prevent crazy symbols in box :) You can see all the stuff working on http://yota.rfw.su/ - all the blue rounded buttons with white text on it - calls on-the-fly forms. Thanks for advice and have a nice weekend!

**Comment by cbopp-art** [comment]
You're welcome and thank you, too! :)
