### ISSUE TITLE
Issue with Jquery 3.1.1

### ISSUE THREAD

**Issue by onefasteuro** [cbopp-art/lightcase#91]
When trying to open a blank popup. 
Uncaught Error: Syntax error, unrecognized expression: #

**Comment by fabianrios** [comment]
yes the same happened to me

**Comment by cbopp-art** [comment]
You need to use an empty href instead of a `#` since jQuery 3.x

**Comment by cbopp-art** [comment]
Did it work for you? Can we close this one?
