### ISSUE TITLE
Too much blank space at the top and bottom

### ISSUE THREAD

**Issue by LeChatNoir69** [cbopp-art/lightcase#92]
Hi there,

Very nice lightbox. We use it on our website but we found that photos height is not optimized regarding browser window. There is a lot of blank at the top and at the bottom.

Is there a simple way to change that ? I've play around with maxHeight but nothing happens.

Thank you ! If I can fix that last point, be sure I'll make a donation and keep on using it :)

**Comment by LeChatNoir69** [comment]
Ok. I've understood that I have to play with maxHeight + shrinkFactor !

Cool ! Thank you for this amazing library !

**Comment by cbopp-art** [comment]
Hi
Great to hear!
