### ISSUE TITLE
Base64 image string ??

### ISSUE THREAD

**Issue by MxoSibeko** [cbopp-art/lightcase#93]
How can I use lightcase with base64 string. I have my images stored on a database, then I convert the byte array to base64 and display the image on an ASP.NET MVC view (`<img src="data: image/png;base64, .."./>`).

**Comment by AbhijitParate** [comment]
Did it work?

**Comment by cbopp-art** [comment]
You have to call lightcase on the fly, and using the onFinish hook you can add a new image with this base64 encoded string to the DOM, finally a resize has to be triggered to fit the lightcase case with its content.

Example (untested):
```
// On the fly
$('#myLink').click(function (event) {
	event.preventDefault();
	lightcase.start({
		href: '#',
		maxWidth: 640,
		maxHeight: 400,
		onFinish: {
			injectContent: function () {
				var content = '<img src="data: image/png;base64, .." alt="">';
				// Find the innermost element and feed with content
				lightcase.get('contentInner').children().html(content);
				// Do a resize now after filling in the content
				lightcase.resize();
			}
		}
	});
});
```

**Comment by lookitsatravis** [comment]
I know this issue is already closed @cbopp-art, but I have an issue with the solution you posted. It works as expected, except that the `lightcase.resize()` doesn't seem to work. The image is larger than the available maxWidth/maxHeight and the image is not scaled down at all.

What is the proper way to have the injected image scaled to fit the screen?

**Comment by cbopp-art** [comment]
@lookitsatravis maybe you could try something like the example below, because it seems that the browser has not loaded the full image at the point where the resize function gets called.

```
lightcase.get('contentInner').find('img').on('load', function () {
    lightcase.resize();
});
```

**Comment by lookitsatravis** [comment]
@cbopp-art - Thanks for the suggestion. That didn't seem to make a difference, but I was able to solve it by setting a max-width/max-height on the img element equal to the corresponding lightcase option, and that seems to have worked.

Thanks for this excellent library!
