### ISSUE TITLE
How to properly position Title to the right of the photo

### ISSUE THREAD

**Issue by LeChatNoir69** [cbopp-art/lightcase#95]
Hi again,

I have photos with title. I'd like to optimize space and show title to the right of the photos instead of bottom.

I'm trying to make it properly, without hacking your library but I'm not a CSS master and I'm stuck...

I've successfully position the info content to the left of the photo using a CSS override but the info remain to the bottom and I can't find a way to position it to the top.

Any help ?
Thanks :)

**Comment by cbopp-art** [comment]
Hi!

There are more than just one possible way how to do so. Either you make changes to the order of elements via option `markup` (see [this line](https://github.com/cbopp-art/lightcase/blob/master/src/js/lightcase.js#L133), or you could make use of one of the hook functions and prepend the info element to the case so that it becomes the first child.

something like this (untested):
```javascript
onFinish: {
  // the name of the key here is arbitrary and irrelevant
  changeOrderOfInfo: function () {
    lightcase.get('info')
      .prependTo(lightcase.get('case'));
  }
}
```

**Comment by LeChatNoir69** [comment]
Ok thank you. But I'm not enough strong in CSS to set right attributes to the info div and tell the browser "put the info div to the left of the content div and size it to the right side of the viewport"...

This CSS override is good enough for my case study but not really proper I think...

#lightcase-info {
	top: 20%;
	left: 100%;
	margin-left: 15px;
	text-align: center;
	width: 35%;
}

**Comment by LeChatNoir69** [comment]
Hi again,

With this CSS, title is to the right of the photo. It's ok. But when photo is in landscape mode, the title is not entirely displayed. It is cut. Any idea of how solve that ?

**Comment by cbopp-art** [comment]
Have you checked one of my last comments concerning hooks?
see also: http://cornel.bopp-art.com/lightcase/documentation/#hooks
