### ISSUE TITLE
Slide effect 

### ISSUE THREAD

**Issue by danilopolani** [cbopp-art/lightcase#96]
Hi, 
there's a way to change the  effect from a photo to another? At this time is like a fade (and slow, not instantly), but I'd like to change to a "slide" effect. 

Thank you!

**Comment by cbopp-art** [comment]
Have you checked out all the options already?
You need to just initialize those links differently or even make use of the `transitionIn` or `transitionOut` if you like to have a different effect for each, in and out.
http://cornel.bopp-art.com/lightcase/documentation/#api

**Comment by DaniloPolani** [comment]
Hi,
yes, but I'd like to have "elastic" effect when open the photo (whatever it is) and "scrollHorizontal" only if change photo in a group/collection, not at "init" or "close".

I thought this would work, but it is not.

```
transition: 'scrollHorizontal',
transitionIn: 'elastic',
transitionOut: 'elastic'
```

**Comment by cbopp-art** [comment]
This is a good hint, thanks! Will take it into consideration.

**Comment by cbopp-art** [comment]
Hi @DaniloPolani 
What you liked to do is possible now! Note that `transitionIn` and `transitionOut` are used to define any arbitrary transition for the next slide in or slide out, respectively.

```
    transition: 'scrollHorizontal',
    transitionOpen: 'elastic',
    transitionClose: 'elastic'
```

**Comment by DaniloMeritocracy** [comment]
Great! I will test it in next days.

Thank you!

**Comment by cbopp-art** [comment]
@danilopolani @DMeritocra Has it solved your issue so far?
