### ISSUE TITLE
Closing Lightcase on mobile forces site to top of page

### ISSUE THREAD

**Issue by kraynijj** [cbopp-art/lightcase#97]
Hi there. Having some troubles when closing out of lightcase on mobile (max-width: 640px). This action forces the site to scroll all the way back to the top, thus making the user have to scroll back down to where they initially were. Any ideas on how to fix? Thanks!

**Comment by cbopp-art** [comment]
Hi!
Lightcase does actually keep the scroll position even on smaller breakpoints. It must be something related to your custom implementation.

**Comment by kraynijj** [comment]
Sure thing.
[https://jsfiddle.net/u7yun186/9/](https://jsfiddle.net/u7yun186/9/)

To replicate the problem:
• Make sure the jsfiddle output window is sized small enough to render the mobile lightcase
• Scroll to middle of output content to find button
• Once lightcase has loaded the content (dummy text), scroll to the bottom of the content
• Scroll back to the top of the lightcase content
• Click the X in the top right to close lightcase
• Result: Main content has been scrolled back up to the top

Hopefully this helps! Thanks!

**Comment by cbopp-art** [comment]
Hi!
This issue has been fixed.

Thanks again
