### ISSUE TITLE
Collection with only one a tag

### ISSUE THREAD

**Issue by Messa1** [cbopp-art/lightcase#98]
Is it possible to only use one a tag and use collection for more images.

```
<a href="" data-lc-href="path/to/media1_small.jpg, path/to/media1_large.jpg 2x" data-rel="lightcase">Your link description or thumb</a>
<a href="" data-lc-href="path/to/media2_default.jpg, path/to/media2_small.jpg 320w, path/to/media2_small_2x.jpg 320w 2x" data-rel="lightcase">Link</a>
```

```
<a href="" data-lc-href="path/to/media1_small.jpg, path/to/media1_large.jpg 2x" data-rel="lightcase">Link</a>

<script>
...
item for lightcase ({
data-lc-href="path/to/media2_default.jpg, path/to/media2_small.jpg 320w, path/to/media2_small_2x.jpg 320w 2x",
data-lc-href="path/to/media3_default.jpg, path/to/media3_small.jpg 320w, path/to/media3_small_2x.jpg 320w 2x",
data-lc-href="path/to/media4_default.jpg, path/to/media4_small.jpg 320w, path/to/media4_small_2x.jpg 320w 2x"
})
...
</script>
```

**Comment by cbopp-art** [comment]
Hi!

I don't know i understand your intension, but an easy way would be to make collections using multiple link tags, but hide all further link tags with e.g. css.

Would this fit your needs, too?

**Comment by Messa1** [comment]
Yeah, but thats the thing i don’t want to hide it with css.
Something like that, is that possible?

https://jsfiddle.net/62p3jb54/ <https://jsfiddle.net/62p3jb54/>

Best Regards
Mit freundlichen Grüßen
Matthias

               <http://www.matthiasgmeiner.com/>         	
   <http://www.matthiasgmeiner.com/>full service agentur

matthias@matthiasgmeiner.com <mailto:matthias@matthiasgmeiner.comm>
www.matthiasgmeiner.com <http://www.matthiasgmeiner.com/>
0660 50 36 470

**Comment by cbopp-art** [comment]
This is not possible, but something like this:
https://jsfiddle.net/62p3jb54/1/

**Comment by Messa1** [comment]
Ah okay so i need to add it like hidden elements?
Maybe you can add this as a feature request ;)
When you told me how much this will cost to develop,
i can talk to my customer :) If it possible to make something like i need :)
Mit freundlichen Grüßen
Matthias

               <http://www.matthiasgmeiner.com/>         	
   <http://www.matthiasgmeiner.com/>full service agentur

matthias@matthiasgmeiner.com <mailto:matthias@matthiasgmeiner.comm>
www.matthiasgmeiner.com <http://www.matthiasgmeiner.com/>
0660 50 36 470

**Comment by Messa1** [comment]
Oky that works. Only one problems is left.
I use there `data-rel="lightcase:gallery-ID"` The ID is replaced by php.
So if i click the link i got one empty "slide" cause it counts also the empty a tag.
Can you show me a fix for that?

**Comment by Messa1** [comment]
Also smaller image are not loading if i test it on mobile devices.

In the lightbox:
`<img src="/160402_028-1024x691.jpg" style="max-width: 414px; max-height: 736px;">
`

Code:
`<a href=" " data-lc-href="/160402_029.jpg, /160402_029-1024x691.jpg 1024w, /160402_029-300x202.jpg 300w, /160402_029-300x202@2x.jpg 600w" data-rel="lightcase:gallery-91" style="display: none;"></a>
`

**Comment by cbopp-art** [comment]
Could you probably provide an example demo? it is quite hard to reproduce your issues.

**Comment by Messa1** [comment]
@cbopp-art i send you the link per mail
