### ISSUE TITLE
Dynamic List of Images

### ISSUE THREAD

**Issue by sayontan** [cbopp-art/lightcase#99]
Hi,
This is more of a help request rather than an issue. I have looked through the documentation but wasn't able to find something that matches this behaviour. Basically, I am looking to replicate the behavior in the "Load Slides Dynamically" section here: http://brutaldesign.github.io/swipebox/#dynamic.

Some background: I am the author of a WordPress plugin called Photonic, which fetches images from various sources such as Smugmug, Flickr, 500px and Zenfolio, and I have integrated a bunch of lightbox scripts within it. Now, I have a feature wherein a user can display album thumbnails, and when the album thumbnails are clicked, the plugin makes a call to the service provider and fetches all the images in the album. Now, some lightbox scripts (Swipebox, PrettyPhoto, BlueImp, FancyBox2) are capable of taking an array of objects, then rendering them in a lightbox right away. 

You can see a demo here: http://aquoid.com/news/plugins/photonic/smugmug/smugmug-albums/, where I use Swipebox. But without this sort of a capability I have to put in an interim step, where all the images in an album are displayed in an overlaid panel, then I click on a thumbnail in the panel to launch the lightbox.

Is this behaviour supported? Even if this is not available as is, is there a way to handle it through the existing API, e.g. by means of an event? Can the "ajax" feature be used for this?

Many thanks for any pointers that you can provide!

**Comment by cbopp-art** [comment]
Hi!
No, exactly the same configuration is not (yet) possible with lightcase. Do you want something similar which was mentioned in #98?
If yes, you probably could take a look to the following fiddle. It is just a workaround:
https://jsfiddle.net/62p3jb54/1/

**Comment by sayontan** [comment]
Thanks for the response!

This is interesting - basically I can modify the DOM with the new elements, then invoke LC? I can give that a shot. I believe this approach was proposed for another library that I support (Colorbox).

Thanks again, and if you plan on putting in the sort of configuration that I requested, can you post back on this thread?

**Comment by sayontan** [comment]
I am closing this, since the proposed workaround does perfectly! Thanks for your prompt response!
